Hamza/models address model
uwblueprint/childrens-aid-society pull request #10
Opened 2022-06-02 02:17 UTC by hamza-yusuff

## Notion ticket link

[https://www.notion.so/uwblueprintexecs/Create-addresses-model-11e335fdac594c7bbbebdde90723294e]

## Implementation description
* Created address,py file inside models
* Created the model for addresses table inside the address.py file
* Ran migration and upgraded the database

## Steps to test
1. Access the database - docker exec -it cas_py_backend /bin/bash
2. Run the command - SELECT * FROM addresses;
3. If you see the table addresses with the necessary columns, then the change should have been made.

2022-06-02 02:53 UTC, jennchenn requested changes
tested it out and looks good!

2022-06-02 02:53 UTC, jennchenn commented on backend/python/app/models/address.py
> +        # define the entities table
nit: remove this comment or change to `addresses` table

2022-06-02 02:53 UTC, jennchenn commented on backend/python/app/models/address.py
> +            # if it's a regular column, extract the value
nit: remove the comments here and on the lines below (they're already in the other model files, they don't need to be repeated in all new model files)

2022-06-02 02:53 UTC, jennchenn commented on backend/python/app/models/address.py
> +    latitude = db.Column(db.Numeric(8, 6), nullable=False)
can you make these `nullable=True` instead? you will need to adjust the migration file as well

2022-06-02 03:36 UTC, jennchenn requested changes

2022-06-02 03:36 UTC, jennchenn commented on backend/python/app/models/address.py
> +    latitude = db.Column(db.Numeric(8, 6), nullable=False)
ahh sorry github did not tie my comment to the line properly i meant to comment only on the latitude and longitude fields 🙏

2022-06-02 03:36 UTC, jennchenn commented on backend/python/app/models/address.py
> +
nit: remove empty line

2022-06-02 03:36 UTC, jennchenn commented on backend/python/app/models/address.py
> +
nit: remove empty line

2022-06-05 05:11 UTC, hamza-yusuff commented
Sorrry about the PR name, completely forgot how I am supposed to do the naming ?

2022-06-05 15:22 UTC, jennchenn commented
> Sorrry about the PR name, completely forgot how I am supposed to do the naming ?

you can either use the ticket name/just something that is more descriptive of what you're doing - the PR name is what is going to show up in the commit history in the main branch so it would be good to just have it as descriptive as possible :)

2022-06-05 17:44 UTC, jennchenn approved these changes
lgtm!!

2022-06-05 17:45 UTC, merged