[kai/intake-post-route] Implement POST /intake route
uwblueprint/childrens-aid-society pull request #108
Opened 2022-11-16 23:44 UTC by kai-wei-mo

## Notion ticket link

[Ticket Name](https://www.notion.so/uwblueprintexecs/Task-Board-db95cd7b93f245f78ee85e3a8a6a316d)

## Implementation description
* 

## Steps to test
1.

## What should reviewers focus on?
* 

## Checklist
- [ ] My PR name is descriptive and in imperative tense
- [ ] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [ ] I have run the appropriate linter(s)
- [ ] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2022-12-23 21:27 UTC, jennchenn requested changes
lots of good work here!! did a pass through the `intake_routes.py` file to hopefully clear up some data issues

let me know what seems reasonable to tackle in this PR

2022-12-23 21:27 UTC, jennchenn commented on backend/python/app/rest/intake_routes.py
> +# @validate_request("CreateIntakeDTO")
does the validation not work for this?

2022-12-23 21:27 UTC, jennchenn commented on backend/python/app/rest/intake_routes.py
> +        "user_id": 1,  # ?
this should come from the request data

2022-12-23 21:27 UTC, jennchenn commented on backend/python/app/rest/intake_routes.py
> +        "intake_status": "ACCEPTED",
default status should be `IN_PROGRESS`

2022-12-23 21:27 UTC, jennchenn commented on backend/python/app/rest/intake_routes.py
> +        "denial_reason": None,  # ?
these fields should be updated later - is there an issue with leaving them blank?

2022-12-23 21:27 UTC, jennchenn commented on backend/python/app/rest/bad.sh
> +curl -X POST -H "Content-Type: application/json" -d @bad.json http://localhost:5000/intake > bad.html
are these scripts going to be removed prior to merging / do they get run somewhere in the test suite?

2022-12-23 21:27 UTC, jennchenn commented on backend/python/app/rest/intake_routes.py
> +            "is_default": False,  # ?
`False` is correct

perhaps the service https://github.com/uwblueprint/childrens-aid-society/blob/540c85cc1670ea406890dd6de55f3ea821a273e8/backend/python/app/services/implementations/familial_concern_service.py#L48-L59 should make a call to `get_familial_concern` first to verify it doesn't add the same concern in twice

2022-12-23 21:27 UTC, jennchenn commented on backend/python/app/rest/intake_routes.py
> +            # "is_default": False,
i think these commented lines can be removed if those are the default values already

2022-12-23 21:27 UTC, jennchenn commented on backend/python/app/rest/intake_routes.py
> +        shortTermGoal = {
i would suggest naming this something else to avoid confusion (since you use `for shortTermGoal in shortTermGoals` already

2022-12-23 21:27 UTC, jennchenn commented on backend/python/app/rest/intake_routes.py
> +            "daytime_contact_id": 1,  # ?
`daytime_contact_id` comes from the above daytimeContact that was added

2022-12-23 21:27 UTC, jennchenn commented on backend/python/app/rest/intake_routes.py
> +        child_obj = {
my bad some updates need to be made to child model
1. combine `first_name` and `last_name` to just `name`
2. remove `child_service_worker_id` and replace with `serviceWorker`
3. remove `has_kinship_provider` and `has_foster_placement` (i think these can be inferred from the rest of the data)

2022-12-23 21:27 UTC, jennchenn commented on backend/python/app/rest/intake_routes.py
> +                "address": "1234 Test St",
these should come from the data as well

2022-12-23 21:27 UTC, jennchenn commented on backend/python/app/rest/intake_routes.py
> +        concerns = child["childInfo"]["concerns"]
this should map to `ChildBehavior`

2022-12-23 21:27 UTC, jennchenn commented on backend/python/app/rest/intake_routes.py
> +    familialConcerns = request.json["programDetails"]["familialConcerns"]
an entry would also need to be added to `intakes_concerns`

2022-12-23 21:27 UTC, jennchenn commented on backend/python/app/rest/intake_routes.py
> +    for shortTermGoal in shortTermGoals:
an entry would also need be to added to `intakes_goals`

2022-12-23 21:27 UTC, jennchenn commented on backend/python/app/rest/intake_routes.py
> +    longTermGoals = request.json["programDetails"]["longTermGoals"]
same comments as for shortTermGoals

2022-12-23 21:27 UTC, jennchenn commented on backend/python/app/rest/intake_routes.py
>  def create_intake():
not sure if it'd be better to move all this logic out into a service rather than polluting this file so it's easier to see all the intake routes at a glance here - thoughts?

2023-05-28 16:15 UTC, bowenzhu1 commented
i should probably clean up the migrations

2023-06-01 22:06 UTC, merged