Added dummy intake route (Julianne + Juthika)
uwblueprint/childrens-aid-society pull request #11
Opened 2022-06-02 02:29 UTC by juthikahoque

## Notion ticket link

[Add dummy create /intakes route](https://www.notion.so/uwblueprintexecs/Add-dummy-create-intakes-route-26e861b0610b4a6f9f47f9d2e2f5473a)

## Implementation description
* created functions with dummy content for a dummy intake route

## Steps to test
1. run this command: `docker exec -it cas_py_backend /bin/bash -c "pip install -e . && pytest"` to make sure that all tests pass (which it should because it is hardcoded to pass)
2. run this command: `curl -X POST http://localhost:5000/intake` to make sure that the object returned is `{"status": "ok"}`

## What should reviewers focus on?
* nothing in particular, but maybe focus on the new files added

## Checklist
- [ ] My PR name is descriptive and in imperative tense
- [ ] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [ ] I have run the appropriate linter(s)
- [ ] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2022-06-02 02:53 UTC, juthikahoque commented
i tried squashing some commits together and in the process it added more commits instead - it should still be fine tho!

2022-06-02 03:18 UTC, jennchenn requested changes
woo first PR 🌟 a few comments

i like using fixup for small changes:
`git commit --fixup <hash of commit your fixing>`
you can also try:
`git rebase -i HEAD~13` or `git rebase -i main` but it's fine for now (we do squash commits when merging into main anyway so it doesn't really matter how many commits there are, just for readability for reviewers)

2022-06-02 03:18 UTC, jennchenn commented on backend/python/app/rest/intake_routes.py
> +# define instance of EntityService
nit: delete

2022-06-02 03:18 UTC, jennchenn commented on backend/python/app/rest/intake_routes.py
> +# from ..middlewares.validate import validate_request
i think you can safely uncomment these

2022-06-02 03:18 UTC, jennchenn commented on backend/python/app/rest/intake_routes.py
> +blueprint = Blueprint("intake", __name__, url_prefix="/intake")
nit:
```suggestion
blueprint = Blueprint("intake", __name__, url_prefix="/intakes")
```

2022-06-02 03:18 UTC, jennchenn commented on backend/python/app/services/implementations/intake_service.py
> +    def __init__(self, logger, file_storage_service: IFileStorageService):
```suggestion
    def __init__(self, logger):
```

you can also initialize the logger like in the `user_service`
https://github.com/uwblueprint/childrens-aid-society/blob/0c7838db69596a1b3d45f7d70f0be8bd6492ee8b/backend/python/app/services/implementations/user_service.py#L9-L21

2022-06-02 03:18 UTC, jennchenn commented on backend/python/app/services/interfaces/intake_service.py
> +    """
nit: go through and rename `entity`->`intake`

2022-06-03 00:22 UTC, jennchenn commented on backend/python/app/rest/intake_routes.py
> +    return (
also feel free to change the body to just be a `pass`

2022-06-03 01:39 UTC, jennchenn reviewed
nice work! once you resolve these small things should be good to merge!

2022-06-03 01:39 UTC, jennchenn commented on backend/python/app/services/interfaces/intake_service.py
> +        """Create a new Entity object
nit:
```suggestion
        """Create a new Intake object
```

2022-06-03 01:39 UTC, jennchenn commented on backend/python/app/rest/intake_routes.py
> +from flask import Blueprint, current_app, jsonify, request
nit: remove unused imports
```suggestion
from flask import Blueprint
```

2022-06-03 01:39 UTC, jennchenn commented on backend/python/app/rest/intake_routes.py
> +
nit: remove the first two lines in this file
```suggestion
```

2022-06-03 01:39 UTC, jennchenn commented on backend/python/app/rest/intake_routes.py
> +# @validate_request("IntakeDTO")
nit: uncomment these two lines
```suggestion
@require_authorization_by_role({"User", "Admin"})
@validate_request("IntakeDTO")
```

2022-06-05 15:42 UTC, jennchenn approved these changes
lgtm!! nice work 🚀

2022-06-05 15:46 UTC, merged