Ivan/attendance models
uwblueprint/childrens-aid-society pull request #129
Opened 2023-01-30 02:04 UTC by IvanYu327

## Notion ticket link

[Create Attendance initial schema/model](https://www.notion.so/uwblueprintexecs/Create-Attendance-initial-schema-model-1e496cb340eb4651982a5a64d81333ea)

## Implementation description
* Create new models for the attendance sheet and the attendance records on it

## Steps to test
1. 

## What should reviewers focus on?
* new models `attendance_sheets.py` and `attendance_records.py`

## Checklist
- [ ] My PR name is descriptive and in imperative tense
- [ ] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [ ] I have run the appropriate linter(s)
- [ ] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2023-02-05 04:49 UTC, bowenzhu1 approved these changes
this looks good! 

before merging, I was wondering if the migration command worked? did it generate a migration file anywhere?

2023-02-05 05:02 UTC, IvanYu327 commented
> this looks good!
> 
> before merging, I was wondering if the migration command worked? did it generate a migration file anywhere?

Yeah, it made a file under `versions`

2023-02-05 05:24 UTC, bowenzhu1 commented
> > this looks good!
> > before merging, I was wondering if the migration command worked? did it generate a migration file anywhere?
> > ![image](https://user-images.githubusercontent.com/85257356/216802681-7451787f-8f2d-4f18-9309-67e5d41d3d8b.png)
> 
> Yeah @bowenzhu1

I think you can add the migration file to this PR, and we should probably do it for any model changes. pls request another review from me once you do just so i can take a look

thanks!

2023-02-16 01:22 UTC, bowenzhu1 requested changes
some typos I just noticed, could you also add the migration file and then we can merge this?

2023-02-16 01:22 UTC, bowenzhu1 commented on backend/python/app/models/__init__.py
> +    from .attendence_sheets import AttendanceSheets
noticed some small fixes to make: typo here attendance

2023-02-16 01:22 UTC, bowenzhu1 commented on backend/python/app/models/attendance_records.py
> +attendance_enum = db.Enum("PRESENT", "CANCELLED", "NO_SHOW", name="attendace")
typo at the end here as well

2023-02-16 02:59 UTC, bowenzhu1 reviewed
hm im not sure why the linter is failing, it's giving errors for :
`would reformat /home/runner/work/childrens-aid-society/childrens-aid-society/backend/python/migrations/versions/2022-07-03_57f14d8ff8bf_condense_goals_and_concerns_models.py
would reformat /home/runner/work/childrens-aid-society/childrens-aid-society/backend/python/tests/functional/test_access_type_service.py
would reformat /home/runner/work/childrens-aid-society/childrens-aid-society/backend/python/tests/functional/test_branch_service.py`

but those aren't even in this PR, lmk if u can fix it or if u get stuck on this linting issue

2023-02-18 14:47 UTC, IvanYu327 commented
>  @bowenzhu1 Not sure how to fix it, the linter is fine on my local repository and I don't see these changes that I'm supposed to make.



> hm im not sure why the linter is failing, it's giving errors for : `would reformat /home/runner/work/childrens-aid-society/childrens-aid-society/backend/python/migrations/versions/2022-07-03_57f14d8ff8bf_condense_goals_and_concerns_models.py would reformat /home/runner/work/childrens-aid-society/childrens-aid-society/backend/python/tests/functional/test_access_type_service.py would reformat /home/runner/work/childrens-aid-society/childrens-aid-society/backend/python/tests/functional/test_branch_service.py`
> 
> but those aren't even in this PR, lmk if u can fix it or if u get stuck on this linting issue

2023-02-23 02:14 UTC, bowenzhu1 commented on backend/python/app/models/attendance_sheets.py
> +    cic = db.Column(db.String, nullable=False)
got some new requested updates/changes from client:

- Change CIC to CSW (children’s service worker name, also in referral process)
- Change RIV to FCC (foster care coordinator)
- Change Place to Location
- Change attending_parent to attending_family -> We can keep the enums for now of Mom Dad, but we'll probably change this in the future
- Change Access Worker to Child Family Support Worker

2023-02-23 02:28 UTC, bowenzhu1 commented on backend/python/app/models/attendance_sheets.py
> +    cic = db.Column(db.String, nullable=False)
also checkout https://github.com/uwblueprint/childrens-aid-society/pull/149 for the linter issue

2023-02-24 04:31 UTC, IvanYu327 commented on backend/python/app/models/attendance_sheets.py
> +    cic = db.Column(db.String, nullable=False)
@bowenzhu1 Made those changes and linter passed, but the firebase deploy frontend is failing. I didn't even touch the frontend here lmao.

2023-02-28 22:16 UTC, bowenzhu1 approved these changes
tests look good now, should be able to merge

2023-03-01 23:47 UTC, bowenzhu1 requested changes

2023-03-01 23:47 UTC, bowenzhu1 commented on backend/python/app/models/attendance_records.py
> +    child_family_suypport_worker_id = db.Column(
wait typo here

2023-03-02 00:25 UTC, bowenzhu1 approved these changes

2023-03-02 14:19 UTC, merged