Create the Selection Item List component
uwblueprint/childrens-aid-society pull request #132
Opened 2023-02-02 02:38 UTC by deenp03

## Notion ticket link

[Create the Selection Item List component](https://www.notion.so/uwblueprintexecs/Create-the-Selection-Item-List-component-b98bd7a57c894186b0134cba12cdc78b)

## Implementation description
* Created the selection item list selection component and implemented it on the program details page
* Replaced the select component with item list selection component on Court information page
* edited the CustomInput file to make it more abstract

## Steps to test
1.[localhost.](http://localhost:3000/intake)

## What should reviewers focus on?
* Making sure that format is correct
* Component made correctly and abstractively

## Checklist
- [ ] My PR name is descriptive and in imperative tense
- [ ] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [ ] I have run the appropriate linter(s)
- [ ] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2023-02-02 20:00 UTC, bowenzhu1 requested changes
minor comments, good work! hopefully this was a decent learning experience too

2023-02-02 20:00 UTC, bowenzhu1 commented on frontend/src/components/intake/Select.tsx
we should change this file name to match the exported component, CustomSelectField.tsx?

2023-02-02 20:15 UTC, deenp03 commented on frontend/src/components/intake/CourtInformationForm.tsx
> +                  placeholder="Select First Nation heritage status"
what icon should I make it?

2023-02-02 20:44 UTC, bowenzhu1 commented on frontend/src/components/intake/CourtInformationForm.tsx
> +                  placeholder="Select First Nation heritage status"
should be same as the other ones, `                  iconRight={<Icon as={ChevronDown} />}`

2023-02-03 01:49 UTC, bowenzhu1 approved these changes
nice work!

2023-02-03 01:50 UTC, merged