Intake footer
uwblueprint/childrens-aid-society pull request #134
Opened 2023-02-04 08:46 UTC by TW1234567

## Notion ticket link

[Create intake form footer navigation component](https://www.notion.so/uwblueprintexecs/134e1f159caa4f73939d11a700c325ad?v=39cf7d5a98384eb9af2bff2265d0ac8a&p=3e8a3cb2f18742fa91e7f69326a78bdc&pm=s)

## Implementation description
* Create footer component which is places in each individual registration page. 
* Footer handles navigation and saving state on click
* Add header stepper to each individual page
* Stepper handle navigation and saving state on click

## Steps to test
1. Edit fields and navigate via either stepper or footer. Notice that the fields (except for Individual details) page is being updated.
[Untitled_ Feb 4, 2023 3_44 AM.webm](https://user-images.githubusercontent.com/117593511/216758018-2a22fa2a-dd64-4031-9d58-b29642c89d5d.webm)

## What should reviewers focus on?
* I didn't handle saving state for individual details because I felt the implementation was rather involved and out of the scope of this PR 
* I noticed that Eugene had worked on some button features for hiding buttons on read only. I remove those code bits and just added buttons via the footer
* The need to have a previous button within the footer feels rather important to me. Especially int he case of the the review page where a header stepper is not provided, I feel that the UI would look clearer having the previous button in the footer and not in the nested page component. 
* I didn't implement the clear page button feature. This was because the previous [PR being built on-top of](https://github.com/uwblueprint/childrens-aid-society/pull/95) didn't mention such requirement.

## Checklist
- [ ] My PR name is descriptive and in imperative tense
- [ ] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [ ] I have run the appropriate linter(s)
- [ ] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2023-02-05 05:20 UTC, bowenzhu1 requested changes
phew thanks for putting this together! looks good overall - i addressed most of your concerns + requested some changes (such as adding wrappers). lmk if you have questions

oh also sorry for the merge conflict lol, I just edited the ReferralForm css grid spacing a little in my merged PR

2023-02-05 05:20 UTC, bowenzhu1 commented on frontend/src/components/intake/IntakeFormFooter.tsx
> +      </Button>
can we add the right arrow icon beside the Next section button? ex. https://www.figma.com/file/1obAgfYZ639hpKXV1ZP7hJ/3.-FeatureSets-%3E-Case-intake?node-id=1412%3A779304&t=Wf9212d8RydGMplg-0

2023-02-05 05:20 UTC, bowenzhu1 commented on frontend/src/components/intake/ReviewCaseForm.tsx
> +        nextBtnTxt="Next"
this should be Submit case, and we should hide the clear button.

I don't think we **need** a previous button, since there are edit buttons to direct the client to previous steps.

2023-02-05 05:20 UTC, bowenzhu1 commented on frontend/src/components/pages/IntakePage.tsx
>            />
hm, for this entire function and files in general, can we make wrapper components?

Ex. instead of calling ReferralForm we call ReferralFormStep, where ReferralFormStep is basically just:
`<Stepper>
        <ReferralForm>
</Stepper>`

ps. also see the comment below for the Container/stepper sizing

This will make it so we can reuse the ReferralForm components elsewhere. like in the Review screen. Currently it has the stepper in it lol 
![image](https://user-images.githubusercontent.com/43287170/216802791-24717577-1f72-407b-b323-7a99184ea596.png)

2023-02-05 05:20 UTC, bowenzhu1 commented on frontend/src/components/pages/IntakePage.tsx
>          <Container maxWidth="container.xl" padding="30px 96px">
if we change the renderDetailsForm to call wrapper components (mentioned in above comment), we can maintain the original stepper size by removing this container here, and just calling it in each wrapper component I think?

So now the wrapper ReferralFormStep could look like 
`<Stepper><Container> <ReferralForm>...  </Container> </Stepper>`

2023-02-05 05:20 UTC, bowenzhu1 commented on frontend/src/components/intake/CourtInformationForm.tsx
> +        showClearPageBtn={!!true}
is this boolean cast !! needed? I think just passing {true} should work

2023-02-05 05:20 UTC, bowenzhu1 commented on frontend/src/components/intake/CourtInformationForm.tsx
> +        isStepComplete={() => true}
lol this makes sense but just looks funny rn. can we add a comment here along the lines of // TODO: validate form

2023-02-05 05:20 UTC, bowenzhu1 commented on frontend/src/components/intake/ReviewCaseForm.tsx
> +    nextStep();
let's add a TODO here, since this nextStep() doesn't do anything right now

2023-02-05 23:50 UTC, TW1234567 commented on frontend/src/components/intake/CourtInformationForm.tsx
> +        showClearPageBtn={!!true}
Nope, will be removed

2023-02-05 23:54 UTC, TW1234567 commented on frontend/src/components/intake/ReferralForm.tsx
> +        nextBtnTxt="Next"
A little confused. I think "nextBtnTxt" should be "Next"

2023-02-05 23:56 UTC, TW1234567 commented on frontend/src/components/intake/IntakeFormFooter.tsx
> +      {showClearPageBtn ? (
I'll change to `showClearPageBtn && <Button>`

2023-02-07 01:12 UTC, bowenzhu1 approved these changes
looks good!! maybe we'll revisit the stepper width thing, but this is good to merge. good work and thanks for debugging thru everything

2023-02-08 15:21 UTC, merged