implement 'Other Permitted Individuals' add and delete
uwblueprint/childrens-aid-society pull request #152
Opened 2023-02-27 00:23 UTC by xiongjasmine

## Notion ticket link

[Integrate Other Permitted Individuals add and delete](https://www.notion.so/uwblueprintexecs/Integrate-Other-Permitted-Individuals-add-and-delete-5d1197d13fa74173ae5bec614d217df3)

## Implementation description
* Implemented add and delete for 'Other Permitted Individuals' section
* Added `DeleteConfirmationModal.tsx` which is a modal that asks the user if they're sure they wanna delete the item
* 'View and edit details' implementation is not completed - this is still WIP so I may do this is a separate PR

## Steps to test
1. Go to `/intake` and go to 'Program Details' in the stepper
2. Click the 'Add' button at the bottom
3. Enter individual info and save it
4. Try adding more individuals and try deleting them too

## What should reviewers focus on?
* Check that you are able to add individuals
* Make sure the correct UI appears when the list of permitted individuals is empty
* Check that the delete button makes a modal pop up and check that the name in the modal is correct
* Check that the right individual deletes

## Checklist
- [x] My PR name is descriptive and in imperative tense
- [x] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [x] I have run the appropriate linter(s)
- [x] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2023-03-05 06:27 UTC, bowenzhu1 requested changes
left some comments, lmk if you have questions.

hows the other part of this going btw (view and edit details?) lmk if you're stuck there, but also 
just a heads up that you might end up with some merge conflicts with eugene's PR for the similar view and edit details functionality depending on if you try to implement it a different way

2023-03-05 06:27 UTC, bowenzhu1 commented on frontend/src/components/intake/DeleteConfirmationModal.tsx
> +      <ModalComponent
is there a way to make this component more similar to the designs? i.e. smaller box, text fills entire width
![image](https://user-images.githubusercontent.com/43287170/222944485-fc59e556-b9df-47b1-b9cc-0f326f03cb5a.png)

2023-03-05 06:27 UTC, bowenzhu1 commented on frontend/src/components/intake/PermittedIndividualsForm.tsx
> +  if (permittedIndividuals.length === 0) {
a slightly cleaner way instead of having two return statements doing `if ... { return }`, would be using a ternary (ex. `return ( {condition ? <first return stuff/> : <second return stuff/>})`

and that way, I think you'd only need one instance of PermittedIndividualsModal as well

2023-03-05 06:27 UTC, bowenzhu1 commented on frontend/src/components/pages/IntakePage.tsx
> +            <ProgramForm
is there a specific reason we want to have these as two components here?

I think we could just call PermittedIndividualsForm inside of ProgramForm? which would be better

2023-03-05 06:27 UTC, bowenzhu1 commented on frontend/src/components/intake/PromptBox.tsx
> +  editIndividual?: (index: number) => void;
doesn't look like we're passing in this prop anywhere in this PR?

2023-03-05 06:27 UTC, bowenzhu1 commented on frontend/src/components/intake/PromptBox.tsx
> +  if (permittedIndividualDetails && permittedIndividualDetails.length > 0) {
this is a lot of repeat code - and it looks like the only major difference is the deletion confirmation modal it seems?

I think instead of having an entire separate if, return statement w repeat code, we can just add another prop along the lines of `showDeleteModal` and then just add checks/ternaries to existing components like the delete icon onClick

2023-03-12 23:03 UTC, xiongjasmine commented on frontend/src/components/intake/DeleteConfirmationModal.tsx
> +      <ModalComponent
edited `ModalComponent.tsx` for UI changes

2023-03-14 04:50 UTC, bowenzhu1 approved these changes
looks good! amazing work yay

2023-03-14 20:22 UTC, merged