Ivan/multi text input
uwblueprint/childrens-aid-society pull request #155
Opened 2023-03-10 06:05 UTC by IvanYu327

## Notion ticket link

[Create multi-text field component](https://www.notion.so/uwblueprintexecs/Create-multi-text-field-component-9bf15e7f71bc47a2b8423c188c0867cc)

## Implementation description
* Created a div that is an array of divs with an input field at the end to simulate a single input field with tags
* Created autocomplete to select tags
* Ability to add and delete tags with enter and delete keypresses

## Steps to test
1. go to `http://localhost:3000/intake`
2. go to the Program details
3. Enter Familial concerns
4. Entering text should behave like a text input
5. Pressing enter with text should create a tag
6. Pressing enter without text should do nothing
7. Pressing backspace while there's no text should delete the last tag
8. Pressing backspace while there is text should backspace text as usual
9. Presssing the X on a tag should delete it
10. Clicking on the text input should open the autocomplete
11. Clicking autocomplete option should add that tag to the field
12. Entering text that is not on the suggestions should show no autocomplete

## What should reviewers focus on?
* `MultiTextInput.tsx`

## Checklist
- [ ] My PR name is descriptive and in imperative tense
- [ ] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [ ] I have run the appropriate linter(s)
- [ ] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2023-03-16 00:27 UTC, bowenzhu1 requested changes
great work! left some comments + follow up notes from our discord talk

2023-03-16 00:27 UTC, bowenzhu1 commented on frontend/src/components/common/MultiTextInput.tsx
> +  setState: (e: string[]) => void;
let's rename this to be a bit more descriptive, maybe `(newValue: string[]) => void` or something

2023-03-16 00:27 UTC, bowenzhu1 commented on frontend/src/components/common/MultiTextInput.tsx
> +  }, []);
do we need this? I though we're already setting showAutoComplete to false when initializing the state

2023-03-16 00:27 UTC, bowenzhu1 commented on frontend/src/components/common/MultiTextInput.tsx
> +  }, []);
some bugs with displaying the autocomplete as mentioned via discord (it shows it on initial render + when clicking on other random form fields)

2023-03-16 00:27 UTC, bowenzhu1 commented on frontend/src/components/common/MultiTextInput.tsx
> +                <Box
change style to match the style of existing selector tags

2023-03-16 00:27 UTC, bowenzhu1 commented on frontend/src/components/common/MultiTextInput.tsx
> +              onFocus={() => setShowAutocomplete(true)}
this onFocus doesn't seem to be performing as expected

2023-03-16 00:27 UTC, bowenzhu1 commented on frontend/src/components/common/MultiTextInput.tsx
> +        display={showAutocomplete && filteredOptions.length > 0 ? "" : "none"}
can we also add a way to disable this via a prop like `readOnly` - so there's no way to input or see the list

2023-03-22 05:59 UTC, IvanYu327 commented
Added the short/long term goals things here too. Testing them is the same, just that there are now 3 MultiTextInput components on the Program Details form to check instead of 1.

2023-03-22 21:48 UTC, bowenzhu1 approved these changes
looks good now! awesome work 

there's one small minor behavior on my end where I can select the end of the component textbox and it seems like i'm able to type. Not an issue really, but feel free to spend ~5 minutes poking around at it. picture below for reference:
![image](https://user-images.githubusercontent.com/43287170/227046074-7cb448ba-fd46-4654-9361-9a4dee234224.png)

2023-03-26 21:45 UTC, merged