Create AttendanceRecordDTO
uwblueprint/childrens-aid-society pull request #158
Opened 2023-03-12 23:34 UTC by Ezzhingy

## Notion ticket link

[Create AttendanceRecord DTO](https://www.notion.so/uwblueprintexecs/134e1f159caa4f73939d11a700c325ad?v=39cf7d5a98384eb9af2bff2265d0ac8a&p=e71537025547413b8769ed2cc0003533&pm=s)

## Implementation description
* Create AttendanceRecordDTO + validation

## Steps to test
1.

## What should reviewers focus on?
* `attendance_record_dto.py`
* Check validation

## Checklist
- [x] My PR name is descriptive and in imperative tense
- [x] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [x] I have run the appropriate linter(s)
- [x] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2023-03-13 23:16 UTC, deenp03 requested changes

2023-03-13 23:16 UTC, deenp03 commented on backend/python/app/resources/attendance_record_dto.py
> +
Add validation for id to ensure that it is an int

2023-03-13 23:16 UTC, deenp03 commented on backend/python/app/resources/attendance_record_dto.py
> +            elif len(self.supervision) == 0:
I think this may be unnecessary

2023-03-13 23:16 UTC, deenp03 commented on backend/python/app/resources/attendance_record_dto.py
> +            error_list.append("location must be a list")
```suggestion
            error_list.append("location must be a string")
```

2023-03-13 23:16 UTC, deenp03 commented on backend/python/app/resources/attendance_record_dto.py
> +            elif len(self.attendance) == 0:
like above

2023-03-13 23:16 UTC, deenp03 commented on backend/python/app/resources/attendance_record_dto.py
> +        self.attending_parent = kwargs.get("attending_parent")
should keep key consistent with attending_family

2023-03-13 23:16 UTC, deenp03 commented on backend/python/app/resources/attendance_record_dto.py
> +            elif len(self.attending_parent) == 0:
like above

2023-03-13 23:16 UTC, deenp03 commented on backend/python/app/resources/attendance_record_dto.py
> +            error_list.append("comments must be a string")
Need to add validation for child_family_support_worker

2023-03-14 04:45 UTC, bowenzhu1 requested changes
left comments/followups to Deen's comments

general change: the file name should acc be attendance_records_dto (add an s to record), for consistency

2023-03-14 04:45 UTC, bowenzhu1 commented on backend/python/app/resources/attendance_record_dto.py
> +        self.attending_parent = kwargs.get("attending_parent")
+1, also change the enum (and add a todo comment in the enum to add more types)

2023-03-14 04:45 UTC, bowenzhu1 commented on backend/python/app/resources/attendance_record_dto.py
> +
we actually don't need to validate for id since it should always be generated as an int

2023-03-14 04:45 UTC, bowenzhu1 commented on backend/python/app/resources/attendance_record_dto.py
> +            elif len(self.supervision) == 0:
I think so too, since we're already comparing with the Supervision class - this could instead be an else statement with error msg saying it has to be a valid supervision option or something

2023-03-14 04:45 UTC, bowenzhu1 commented on backend/python/app/resources/attendance_record_dto.py
> +            error_list.append("comments must be a string")
+1, should be an int check

2023-03-16 04:32 UTC, deenp03 approved these changes
Left a couple of small fixes, looks good otherwise

2023-03-16 04:32 UTC, deenp03 commented on backend/python/migrations/versions/2023-03-16_e8d276dc89aa_change_instances_of_attending_parent_to_.py
Is this file necessary?

2023-03-16 16:20 UTC, Ezzhingy commented on backend/python/migrations/versions/2023-03-16_e8d276dc89aa_change_instances_of_attending_parent_to_.py
pretty sure, cause we want to update db column to be "attending_family", not "attending_parent"

2023-03-16 16:32 UTC, deenp03 commented on backend/python/migrations/versions/2023-03-16_e8d276dc89aa_change_instances_of_attending_parent_to_.py
Yes we would need to run the upgrade method once to update all local dbs

2023-03-18 00:32 UTC, bowenzhu1 approved these changes
lgtm!!

2023-03-18 02:57 UTC, merged