add submit case flow
uwblueprint/childrens-aid-society pull request #161
Opened 2023-03-23 02:35 UTC by xiongjasmine

## Notion ticket link

[Add “Submit case” flow](https://www.notion.so/uwblueprintexecs/Add-Submit-case-flow-d3d6b0577a2e4f108533bcbadffba919)

## Implementation description
* WIP don't review

## Steps to test
1.

## What should reviewers focus on?
* 

## Checklist
- [x] My PR name is descriptive and in imperative tense
- [x] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [ ] I have run the appropriate linter(s)
- [ ] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2023-03-30 01:26 UTC, bowenzhu1 requested changes
left some minor things to change and noted some uhhh not great (but acceptable) practices

2023-03-30 01:26 UTC, bowenzhu1 commented on frontend/src/components/pages/IntakePage.tsx
> +              isStepComplete={() => true} // TODO: validate form
do we need this TODO comment here

2023-03-30 01:26 UTC, bowenzhu1 commented on frontend/src/components/pages/IntakePage.tsx
> +              <IntakeHeader
similar comment to your other pr: we want to avoid duplicating component calls/code, and instead we can do conditional passes to the prop (primaryTitle in this case)

2023-03-30 01:26 UTC, bowenzhu1 commented on frontend/src/components/intake/IntakeFormFooter.tsx
> +
we could prob also just add the submit error modal logic here too. i don't rlly like having the modal logic in the footer component lol but i think this is fine if there's no better place

2023-03-30 01:26 UTC, bowenzhu1 commented on frontend/src/components/intake/IntakeFormFooter.tsx
> +          if (nextButtonText === "Submit case") {
i think generally string prop comparison isn't good, and we should technically try to separate this into an enum or something buuuuut this is fine cause its simple and is alrdy an existing prop/component

2023-03-30 17:13 UTC, xiongjasmine commented on frontend/src/components/pages/IntakePage.tsx
> +              <IntakeHeader
i rebased and updated it and it still looks a bit repetitive but i tried to do it in the cleanest way i could. can you check it again and lmk if it's ok?

2023-04-01 15:01 UTC, bowenzhu1 requested changes
small comment for the useDisclosure for SubmitErrorModal, but looks good to merge otherwise

2023-04-01 15:01 UTC, bowenzhu1 commented on frontend/src/components/pages/IntakePage.tsx
> +              <IntakeHeader
yep this looks good! it's still a relatively simple case so i dont think there's that much more we can do without overkilling it

2023-04-02 21:30 UTC, bowenzhu1 approved these changes

2023-04-02 21:31 UTC, merged