Attendance sheet api
uwblueprint/childrens-aid-society pull request #165
Opened 2023-04-03 05:17 UTC by TW1234567

## Notion ticket link

[Implement attendance sheet service](https://www.notion.so/uwblueprintexecs/Implement-attendance-sheet-service-7a942b1ad0f545cfb67db2daf92c3753)

## Implementation description
* Made changes to AttendanceSheetDTO to sync the fields between our DTO and postgress model
* Added CRUD operations to managing Attendance sheets
* Changed the intake_id field of the AttedanceSheetDTO to temporarily decouple from Intake model
* Made unit tests for CRUD operations

## Steps to test
1. Verify unit tests
2. Test endpoints via postman

## What should reviewers focus on?
* 

## Checklist
- [ ] My PR name is descriptive and in imperative tense
- [ ] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [ ] I have run the appropriate linter(s)
- [ ] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2023-04-26 23:46 UTC, bowenzhu1 requested changes
looks good overall, some minor changes requested. overall logic + code structure and quality is good! 

this helps a lot to set up the foundation for our attendance backend

2023-04-26 23:46 UTC, bowenzhu1 commented on backend/python/app/rest/__init__.py
> +    app.register_blueprint(visit_routes.blueprint)
duplicate visit_routes?

2023-04-26 23:46 UTC, bowenzhu1 commented on backend/python/app/services/implementations/attendance_sheet_service.py
> +                    "Empty attendance sheet DTO/None passed to creacreate_attendance_sheet function"
typo here

2023-04-26 23:46 UTC, bowenzhu1 commented on backend/python/app/services/interfaces/attendance_sheet_service.py
> +        """
add `pass` statement here and in below function for code hygiene

2023-04-26 23:46 UTC, bowenzhu1 commented on backend/python/app/services/interfaces/attendance_sheet_service.py
> +    @abstractmethod  # TODO: finish this
can you clarify what the TODO remaining work is here?

2023-04-26 23:46 UTC, bowenzhu1 commented on backend/python/tools/db_seed.py
> +# from ..app.models.caregiver import Caregiver
remove comment

2023-04-26 23:46 UTC, bowenzhu1 commented on backend/python/app/rest/attendance_sheet_routes.py
> +        if intake_id and id:
I think in this case if both are provided, we can prioritize it in the order of id > intake_id.

So this would just behave the same as if only id is provided, since id is the stricter condition

2023-04-27 00:15 UTC, TW1234567 commented on backend/python/app/rest/__init__.py
> +    app.register_blueprint(visit_routes.blueprint)
Yep, will be removed

2023-04-27 00:15 UTC, TW1234567 commented on backend/python/app/services/implementations/attendance_sheet_service.py
> +                    "Empty attendance sheet DTO/None passed to creacreate_attendance_sheet function"
Yep, will remove.

2023-04-27 00:17 UTC, TW1234567 commented on backend/python/app/services/interfaces/attendance_sheet_service.py
> +        """
Thanks for the catch. Will do

2023-04-27 00:18 UTC, TW1234567 commented on backend/python/app/services/interfaces/attendance_sheet_service.py
> +    @abstractmethod  # TODO: finish this
Sorry about that. It was an old comment for myself to finish implementing `delete_attendance_sheet`. This comment will be removed as `delete_attendance_sheet` implementation is finished.

2023-04-27 00:18 UTC, TW1234567 commented on backend/python/tools/db_seed.py
> +# from ..app.models.caregiver import Caregiver
Will do

2023-05-17 23:23 UTC, bowenzhu1 approved these changes

2023-05-17 23:27 UTC, merged