Integrate Add Child flow and child data saving
uwblueprint/childrens-aid-society pull request #171
Opened 2023-04-27 01:02 UTC by Ezzhingy

## Notion ticket link

[Integrate Add Child flow and child data saving](https://www.notion.so/uwblueprintexecs/Integrate-Add-Child-flow-and-child-data-saving-8bbfd18fd7674c7eb166076b4e88c8d9)

## Implementation description
* Created `ChildrenDetails` type, stores child data
* Once user clicks on `Save Child Information`, `ChildrenDetails` gets updated

## Steps to test
1. `console.log` spam

## What should reviewers focus on?
* Make sure `ChildrenDetails` gets updated

## Checklist
- [ ] My PR name is descriptive and in imperative tense
- [ ] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [ ] I have run the appropriate linter(s)
- [ ] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2023-04-27 01:22 UTC, Ezzhingy commented
*lint code breaks cause i never call the state

2023-05-26 05:07 UTC, bowenzhu1 requested changes
some changes requested relating to the eslint issues, but overall looks good to me

also a general suggestion is that eslint warnings shouldn't rlly be ignored - there are cases where u can do `// eslint-disable-next-line` but usually it's better to avoid breaking eslint

2023-05-26 05:07 UTC, bowenzhu1 commented on frontend/src/components/pages/IntakePage.tsx
> +export type Childrens = ChildrenDetails[];
can we define all this in `AddChildPage` instead? I think that would fix a lot of the cyclical import issues

2023-05-26 05:07 UTC, bowenzhu1 commented on frontend/src/components/pages/IntakePage.tsx
> +export type Childrens = ChildrenDetails[];
also can we use `Children` instead of `Childrens` in all cases (childrens feels too wrong LOL)

2023-05-26 05:07 UTC, bowenzhu1 commented on frontend/src/components/intake/IndividualDetailsEntry.tsx
is there a reason we're importing these here for this PR? If not then we can remove these imports from this PR, and save these changes for when we need them

2023-05-28 02:48 UTC, Ezzhingy commented
i kept one instance of "childrens", cause i cant pass "children" in as a prop `children: children` doesn't work

2023-05-28 14:18 UTC, bowenzhu1 reviewed
small follow ups (I'll look to approve and merge this in right after this)

2023-05-28 14:18 UTC, bowenzhu1 commented on frontend/src/components/intake/child-information/AddChildPage.tsx
> +    console.log(childrens);
can we remove this console log

2023-05-28 14:18 UTC, bowenzhu1 commented on frontend/src/components/pages/IntakePage.tsx
> +          childrens={children}
wait i think `children={children}` should work? can we change the field name to `children` then? 

what error is it giving u if it's `children={children}`

2023-06-04 15:49 UTC, bowenzhu1 approved these changes

2023-06-04 16:37 UTC, merged