Kevin y/change status modal frame
uwblueprint/childrens-aid-society pull request #173
Opened 2023-05-26 01:13 UTC by kevinasian122

## Notion ticket link

[Change Status Modal Frame](https://www.notion.so/uwblueprintexecs/134e1f159caa4f73939d11a700c325ad?v=39cf7d5a98384eb9af2bff2265d0ac8a&p=c2319276e71544b4be9c5aceaf54eaa7&pm=s)

## Implementation description
* Used ModalComponent with some input fields as the body, delete is absolute positioning for now because I don't know how to align it with the save button from the ModalComponent otherwise. Nothing to activate the modal for now.
* ![image](https://github.com/uwblueprint/childrens-aid-society/assets/70108329/b106e238-51e9-4680-8bcb-1842e8015b78)

## Steps to test
1.

## What should reviewers focus on?
* Delete button positioning
* Don't know how to style the select dropdown input

## Checklist
- [x] My PR name is descriptive and in imperative tense
- [x] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [x] I have run the appropriate linter(s)
- [x] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2023-05-28 02:39 UTC, bowenzhu1 requested changes
left comments regarding code style + pointers on dropdown and delete button implementation

2023-05-28 02:39 UTC, bowenzhu1 commented on frontend/src/components/dashboard/StatusModal.tsx
> +              borderWidth="1px"
try to reference design more, feels like this can have a bit more padding?

2023-05-28 02:39 UTC, bowenzhu1 commented on frontend/src/components/dashboard/StatusModal.tsx
> +              <Text>Lead: XXX</Text>
add // TODO comment to mention that this will need to be changed for dynamic values

2023-05-28 02:39 UTC, bowenzhu1 commented on frontend/src/components/dashboard/StatusModal.tsx
> +                <Select
this is fine for this pr for now, would add a //TODO as well here to mark as need to change, since you're working on the other ticket for the dropdown

2023-05-28 02:39 UTC, bowenzhu1 commented on frontend/src/components/dashboard/StatusModal.tsx
> +const StatusChange = ({
generally it's good practice to match the name here with the file name - `StatusChangeModal` might be best?

2023-05-28 02:39 UTC, bowenzhu1 commented on frontend/src/components/dashboard/StatusModal.tsx
> +  caseNum?: number;
nit: don't need to abbreviate variables/fields - usually better to write it all out for readability, though it doesn't matter that much here

2023-05-28 02:39 UTC, bowenzhu1 commented on frontend/src/components/dashboard/StatusModal.tsx
> +                  <FormLabel htmlFor="childrenservicesworker">
for ternary checks like this, you shouldn't reuse the code for the entire components - could do it just within the props

i see that you did it for the CustomInput below

2023-05-28 02:39 UTC, bowenzhu1 commented on frontend/src/components/dashboard/StatusModal.tsx
> +                  <FormLabel htmlFor="childrenservicesworker">
should be `childrenServicesWorker` to follow camel case conventions

2023-05-28 02:39 UTC, bowenzhu1 commented on frontend/src/components/dashboard/StatusModal.tsx
> +              <FormLabel htmlFor="meetingnotes">
same here, use camelCase

2023-05-28 02:39 UTC, bowenzhu1 commented on frontend/src/components/dashboard/StatusModal.tsx
> +                id="meetingnotes"
also here for camel case

2023-05-28 02:39 UTC, bowenzhu1 commented on frontend/src/components/dashboard/StatusModal.tsx
> +                variant="primary"
could we implement a new button variant i.e. 'delete' in `buttonStyles` instead of using primary, and then call this here

i think we need to change the hover state a bit more for the delete button, + the shadow options to match the design for this type of button. The primary variant isn't really meant for this design

2023-05-28 02:39 UTC, bowenzhu1 commented on frontend/src/components/dashboard/StatusModal.tsx
> +            {/* save button is part of ModalComponent so don't know how to make delete button aligned */}
okay yea i see what u mean here

the best way to go about this is probably just editing the `ModalComponent`, like u suggested in Discord (mb for saying no to this before). BUT make sure that u edit the ModalComponent in a generic way, and pass in the implementation specific behaviors/styling. Something like an optional prop for leftButton + leftButtonVariant, so that no other calls of ModalComponent break or get affected by the change

2023-05-28 02:39 UTC, bowenzhu1 commented on frontend/src/components/pages/HomePage.tsx
> +import StatusChange from "../dashboard/StatusModal";
change import name here as well to be consistent w file name

2023-05-28 15:23 UTC, kevinasian122 commented on frontend/src/components/dashboard/StatusModal.tsx
> +              borderWidth="1px"
The padding is just set to 32px inside ModalComponent and there's no prop I can pass in to change that, should I maybe change the ModalComponent for optional padding props?

2023-06-02 02:47 UTC, bowenzhu1 requested changes
small comments about conditional logic

2023-06-02 02:47 UTC, bowenzhu1 commented on frontend/src/components/common/ModalComponent.tsx
> +          {leftButtonTitle && leftButtonVariant ? (
do we need the ternary operator here? can we just do `{(leftButtonTitle && leftButtonVariant) && ...` since the ternary second option "" doesnt do anything

2023-06-02 02:47 UTC, bowenzhu1 commented on frontend/src/components/dashboard/StatusModal.tsx
> +        leftButtonTitle={selectedOption === "ARCHIVED" ? "Delete" : ""}
similar comment here, i don't think we need the ternary. We can just conditionally display the left button if we want to or not, with a prop like `showLeftButton`

2023-06-02 02:48 UTC, jess94yng requested changes

2023-06-02 02:48 UTC, jess94yng commented on frontend/src/theme/buttonStyles.tsx
> +          "0px 0px 32px rgba(255, 0, 0, 0.1), 0px 0px 32px rgba(102, 0, 0, 0.2)",
change boxShadow specs to `"0px 0px 16px rgba(255, 0, 0, 0.1), 0px 0px 16px rgba(102, 0, 0, 0.2)"` to match the primary button specs

2023-06-04 15:36 UTC, jess94yng approved these changes
looks good!

2023-06-04 15:36 UTC, merged