Adding CaseOverview Page Skeleton and CaseOverview Footer
uwblueprint/childrens-aid-society pull request #174
Opened 2023-05-28 16:03 UTC by odis43

Adding CaseOverview Page Skeleton and CaseOverview Footer.  This implementation is a start in allowing case information to be seen when clicking on any case.

## Notion ticket link

[Case Overview page skeleton](https://www.notion.so/uwblueprintexecs/Case-Overview-page-skeleton-a45ba23e6f15411f9c1012dc10f3588b?pvs=4)

## Implementation description
* Implemented Case Overview skeleton and a Case Overview Footer, similar to the Intake Footer
* Only the front end has been implemented
* As per the ticket details, the logic has been left untouched

## Steps to test
1. The empty states/boxes for all of Children, Visiting Family, etc. etc. should match the designs
2. The buttons UI should be implemented

## What should reviewers focus on?
* The overall design, compared to the figma design
* If there are any issues with the formatting of the page

## Checklist
- [ x ] My PR name is descriptive and in imperative tense
- [ x ] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [ x ] I have run the appropriate linter(s)
- [ x ] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2023-05-31 03:56 UTC, bowenzhu1 requested changes
could you remove the package-lock.json and yarn.lock with a new commit? (in general we don't need to add these unless you made changes to ur packages)

the pipeline (deploy/tests/lint) are failing because of that it seems

2023-06-04 16:11 UTC, jess94yng commented on frontend/src/components/pages/CaseOverview.tsx
> +          <b style={{ color: "#45464F", fontSize: "12px" }}>
All text styles should be implemented with imported components from textStyles.tsx file

2023-06-04 16:43 UTC, jess94yng requested changes

2023-06-04 16:43 UTC, jess94yng commented on frontend/src/components/pages/CaseOverview.tsx
> +              <h1 style={{ fontSize: "20px", fontWeight: "bold" }}>Children</h1>
The section titles along with empty state messages seem a bit off from the design - see if that can be fixed by using textStyle components

2023-06-04 16:43 UTC, jess94yng commented on frontend/src/components/pages/CaseOverview.tsx
> +            CHILDREN SERVICES OR KINSHIP WORKER
All text styles should be implemented with imported components from textStyles.tsx file

2023-06-04 16:43 UTC, jess94yng commented on frontend/src/components/pages/CaseOverview.tsx
> +      <div style={{ paddingBottom: "100px" }}>
The left and right columns should not take up equal spacing on the page (left column should be slightly larger) - please see spacing details from figma file

2023-06-04 16:43 UTC, jess94yng commented on frontend/src/components/pages/CaseOverview.tsx
> +              <h1 style={{ fontSize: "20px", fontWeight: "bold" }}>Children</h1>
The children container box should be slightly larger than the ones below - please refer to sizing details from figma file

2023-06-04 16:43 UTC, jess94yng commented on frontend/src/components/pages/CaseOverview.tsx
> +              <p>By FirstLast@example.com</p>
Please change this to "By First Last" - I will update the design to reflect this

2023-06-04 16:43 UTC, jess94yng commented on frontend/src/components/pages/CaseOverview.tsx
> +              <p>By FirstLast@example.com</p>
Text inside box seems to be too far up on the left corner - check figma file for spacing / positioning details

2023-06-04 16:43 UTC, jess94yng commented on frontend/src/components/intake/CaseOverviewFooter.tsx
> +          Generate Report (PDF)
Button positioning is off, button also disappears when window is resized

2023-06-04 16:43 UTC, jess94yng commented on frontend/src/components/intake/CaseOverviewFooter.tsx
> +          <Box pr="5px">Archive Case</Box>
Archive button color needs modification - I would suggest making a new button style in buttonStyles.tsx. You can refer to the coloring for the normal and hover states of the delete button in that file.

2023-06-04 16:43 UTC, jess94yng commented on frontend/src/components/pages/CaseOverview.tsx
> +              <p>By FirstLast@example.com</p>
Add a //TODO here for implementing this text field dynamically with case information

2023-06-15 04:44 UTC, bowenzhu1 requested changes
nice work! i think your general implementation approach is good but there are a few major aspects I commented on to change, a lot of which relates to code quality practices. key takeaways to summarize and to change:

- clean up and remove irrelevant logic when copying over code from other places (ex. need to remove a lot of the Intake logic that's in CaseOverviewFooter right now)
- use UI library (ChakraUI) components instead of general html ones, such as using  `<Text>` instead of `<h1>`
- use defined style files instead of hardcoding/manually defining styles, including `textStyles` and `colors`
- make use of props for generic behavior for components (for Button component, icons should be just passed in as a prop instead of having to implement and format components in the body)

2023-06-15 04:44 UTC, bowenzhu1 commented on frontend/src/components/intake/CaseOverviewFooter.tsx
i think we can refactor this file quite a bit, a lot of the footer logic from IntakeFormFooter doesn't really apply here

2023-06-15 04:44 UTC, bowenzhu1 commented on frontend/src/components/intake/CaseOverviewFooter.tsx
> +};
for this logic (next step, clear page, etc.), we shouldn't have it in this footer. Can we remove all of the unnecessary logic/props/functions copied from Intake

The button options for the CaseOverviewFooter should just either be Archive Case or Generate Report.

2023-06-15 04:44 UTC, bowenzhu1 commented on frontend/src/components/intake/CaseOverviewFooter.tsx
> +  } = useDisclosure();
similar to above, I don't think these modals should be in this file

2023-06-15 04:44 UTC, bowenzhu1 commented on frontend/src/components/intake/CaseOverviewFooter.tsx
> +          ref={nextButtonRef}
need to edit this button so that it doesn't use irrelevant intake settings

2023-06-15 04:44 UTC, bowenzhu1 commented on frontend/src/components/intake/CaseOverviewFooter.tsx
> +          <div style={{ paddingRight: "10px" }}>
do we need this div here? It seems to be an extra wrapper.

general feedback: since we're using a UI library like ChakraUI, we shouldn't really be using any native html elements like `<div>` or `<h1>` since there's probably a better ChakraUI component instead of it

2023-06-15 04:44 UTC, bowenzhu1 commented on frontend/src/components/intake/CaseOverviewFooter.tsx
> +          <div style={{ paddingRight: "10px" }}>
similar as above

2023-06-15 04:44 UTC, bowenzhu1 commented on frontend/src/components/pages/CaseOverview.tsx
for all of the text elements, try to use <Text> components and use the styles from `textStyles.tsx`

similarly, when using colors we should be using `colors.tsx` instead of hardcoding the color values directly here

2023-06-15 04:44 UTC, bowenzhu1 commented on frontend/src/components/pages/CaseOverview.tsx
> +          <b style={{ color: "#45464F", fontSize: "12px" }}>
we should replace the components here to not use native html ones, and replace colors to use `colors.tsx` instead of hardcoding

2023-06-15 04:44 UTC, bowenzhu1 commented on frontend/src/components/pages/CaseOverview.tsx
> +                <div style={{ paddingRight: "10px" }}>
when adding icons to buttons, we should be using the `leftIcon` or `rightIcon` props in Button, which uses the Icon component. try to see other places in our code that use this for reference

2023-06-25 05:57 UTC, odis43 commented on frontend/src/components/intake/CaseOverviewFooter.tsx
> +          <div style={{ paddingRight: "10px" }}>
i had that div there to space out the button icon and the text. I scoured the Chakra UI lib and couldn't find anything related to this kind of spacing.

2023-07-07 00:50 UTC, closed without merging

2023-07-07 00:50 UTC, bowenzhu1 commented
overwriten by https://github.com/uwblueprint/childrens-aid-society/pull/187