Build Main Dashboard Case Card Component
uwblueprint/childrens-aid-society pull request #175
Opened 2023-05-28 16:08 UTC by JennyVong

## Notion ticket link

[Main Dashboard Case Cards](https://www.notion.so/uwblueprintexecs/134e1f159caa4f73939d11a700c325ad?v=39cf7d5a98384eb9af2bff2265d0ac8a&p=819164235311446e843fa6b76fcb3b9b&pm=s)

## Implementation description
* make a new component (in a new /component/dashboard folder) for this card so it can be reusable.
* export a new type for all the Case details, and this type should be passed as a prop into our new component.
* The View all icon does not perform an action for now.

## Steps to test
1. pull branch and `import CaseCard from "../dashboard/CaseCard";` into `HomePage.tsx`
2. hardcode dummy card into homepage:
   Pending case: 
    `<CaseCard
        caseTitle="Case 1"
        caseLead="Case Lead"
        date="28/05/2023"
        familyName="family name"
        caseTag="PENDING"
      />`
   Active case: 
    `<CaseCard
        caseTitle="Case 1"
        caseLead="Case Lead"
        date="28/05/2023"
        familyName="family name"
        caseTag="ACTIVE"
      />`
   Submitted case: 
    `<CaseCard
        caseTitle="Case 1"
        caseLead="Case Lead"
        date="28/05/2023"
        familyName="family name"
        caseTag="SUBMITTED"
      />`
   Archived case: 
    `<CaseCard
        caseTitle="Case 1"
        caseLead="Case Lead"
        date="28/05/2023"
        familyName="family name"
        caseTag="ARCHIVED"
      />`

<img width="254" alt="Screenshot 2023-05-28 at 12 07 19 PM" src="https://github.com/uwblueprint/childrens-aid-society/assets/50973299/2bf4aaf3-b717-4893-b812-1382390bb0f0">
<img width="246" alt="Screenshot 2023-05-28 at 12 07 49 PM" src="https://github.com/uwblueprint/childrens-aid-society/assets/50973299/52e3b3a0-39c0-4c3f-9770-11f20e75f96c">
<img width="245" alt="Screenshot 2023-05-28 at 12 08 10 PM" src="https://github.com/uwblueprint/childrens-aid-society/assets/50973299/c75c298b-262e-4cca-8fc9-4b15d50f3b55">
<img width="237" alt="Screenshot 2023-05-28 at 12 08 22 PM" src="https://github.com/uwblueprint/childrens-aid-society/assets/50973299/30385d88-aa92-4955-9628-7d7b355b0d68">

## What should reviewers focus on?
* The card itself does not have a fixed size (i think this is done when formatting cards onto homepage?) 
* case tag should have different colours based on their status
* all fields should be displayed when passing in CaseCard props

## Checklist
- [x] My PR name is descriptive and in imperative tense
- [x] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [x] I have run the appropriate linter(s)
- [x] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2023-06-02 01:32 UTC, bowenzhu1 requested changes
changes requested for clickable behaviour and card sizing - looks good overall!

2023-06-02 01:32 UTC, bowenzhu1 commented on frontend/src/components/dashboard/CaseCard.tsx
> +      <Button
sorry for the mixup - the entire card should actually be clickable (arrow is just an indicator that the card is clickable). So on hover the card gets a shadow + the cursor shows clickable

in general, I think we can just use `onClick` of components if it's available - don't necessarily need to use `Button` for a clickable behaviour

2023-06-02 01:32 UTC, bowenzhu1 commented on frontend/src/components/dashboard/CaseCard.tsx
> +  <Box
in terms of sizing/dimensions, we want to restrict the cards to be basically squares

in that case, could we maybe try hard defining the max width and height to be based on the designs (297 and 289 are the figma values i believe? 

but spacing/arrangement and everything would be handled not in this ticket

2023-06-02 01:32 UTC, bowenzhu1 commented on frontend/src/theme/buttonStyles.tsx
> +    withIcon: {
probably don't need this after changes

2023-06-02 01:32 UTC, bowenzhu1 commented on frontend/src/components/dashboard/CaseCard.tsx
> +  let col;
nit: i think we should keep variable names as full as possible for legibility

2023-06-07 23:50 UTC, bowenzhu1 requested changes
noticed some more small ui fixes to do before merging:
- we should use <Text textStyle="title-medium"> for the case card titles. the text styles should generally match what the text style is on Figma
- I think the card can be set taller vertically, and the text lines can be spaced out more. Feels off from the designs
- ^ a bit related, I think the cards should just have set width/heights. I don't think it should resize based on window size/zoom

2023-06-09 02:37 UTC, jess94yng approved these changes
looks good to me!

2023-06-11 15:50 UTC, bowenzhu1 approved these changes

2023-06-11 15:51 UTC, merged