KevinC/ add logout modal
uwblueprint/childrens-aid-society pull request #180
Opened 2023-06-08 20:28 UTC by kevinchen220

## Notion ticket link

[Implement Log Out Modal and Flow](https://www.notion.so/uwblueprintexecs/Implement-Log-Out-Modal-and-Flow-0119c7c9c45b4d57a82db4493d04b6fb?pvs=4)

## Implementation description
* Added a Log out modal using `ModalComponent`
* Log out modal is controlled by the `Logout` button
* Moved to previous logout function to the confirmation button onClick in the modal
  * Not exactly sure how to test that

## Steps to test
1. Click logout button on the top right of the dashboard
2. See the Logout Modal that pops up

## What should reviewers focus on?
* Whether the logout function is correct

## Checklist
- [x] My PR name is descriptive and in imperative tense
- [x] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [x] I have run the appropriate linter(s)
- [x] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2023-06-11 16:47 UTC, jess94yng requested changes

2023-06-11 16:47 UTC, jess94yng commented on frontend/src/components/common/ModalComponent.tsx
> +  showModalCloseButton = true,
Currently when the log out modal first pops open, the cancel button is in a selected state (blue ring around it) - see if that can be fixed?

2023-06-11 16:53 UTC, bowenzhu1 commented on frontend/src/components/auth/Logout.tsx
> +  const [openModal, setOpenModal] = useState(false);
we could use `useDisclosure` instead here which would be a bit cleaner. - to make use of ChakraUI modal handling logic. you can cmd+shift+f search for other files where we use it for reference. but other than that lgtm

2023-06-13 21:53 UTC, kevinchen220 commented on frontend/src/components/common/ModalComponent.tsx
> +  showModalCloseButton = true,
Looks like that's the default behaviour of ChakraUI modals, the first tab-able element is selected. Not sure if there is an easy fix

2023-06-13 21:57 UTC, kevinchen220 commented on frontend/src/components/common/ModalComponent.tsx
> +  showModalCloseButton = true,
Nevermind I got it to work

2023-06-14 00:56 UTC, bowenzhu1 approved these changes
lgtm to merge

2023-06-16 00:06 UTC, jess94yng approved these changes

2023-06-16 00:10 UTC, merged