Case overview skeleton pr changes
uwblueprint/childrens-aid-society pull request #187
Opened 2023-06-25 15:05 UTC by odis43

## Notion ticket link

[Ticket Name](https://www.notion.so/uwblueprintexecs/Case-Overview-page-skeleton-a45ba23e6f15411f9c1012dc10f3588b?pvs=4)

## Implementation description
* Changes to PR review by Bowen and Jessica. Changes include fixing the design to meet the requirements of the figma document, improving code quality through the use of component based styling and removing unnecessary logic from the footer (caseOverviewFooter)

## Steps to test
1. Check figma documentation for design match up
2. Check code for mistakes in implementation 

## What should reviewers focus on?
* If the design is more suitable as per the figma document

## Checklist
- [x] My PR name is descriptive and in imperative tense
- [ x] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [x ] I have run the appropriate linter(s)
- [ x] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2023-06-30 00:53 UTC, bowenzhu1 requested changes

2023-06-30 00:53 UTC, bowenzhu1 commented on frontend/src/components/intake/CaseOverviewFooter.tsx
> +        height="38px"
do we need to specify the dimensions here? I think the default dimensions should work, which we use for other instances of the button if im not mistaken. lmk if there's a reason for specifying this though

2023-06-30 00:53 UTC, bowenzhu1 commented on frontend/src/components/intake/CaseOverviewFooter.tsx
> +        <div style={{ paddingRight: "10px" }}>
having div wrappers like this is generally not that great of a practice, most components should be able to have CSS applied (like padding) directly onto them

I think the FileText is just a icon though, but in a case like this you can use the <Icon> component and pass in FileText

2023-06-30 00:53 UTC, bowenzhu1 commented on frontend/src/components/intake/CaseOverviewFooter.tsx
> +      <Box flex="1" /> {/* Spacer element */}
in general try to avoid adding components if you dont have to, to reduce clutter/improve code cleanliness.

 i think you can wrap the two buttons in a Box or something and then apply the spacing there.

2023-06-30 00:53 UTC, bowenzhu1 commented on frontend/src/components/intake/CaseOverviewFooter.tsx
> +        background={colors.red[600]}
might be able to use an existing buttonStyle instead of applying the color directly

2023-06-30 00:53 UTC, bowenzhu1 commented on frontend/src/components/pages/CaseOverview.tsx
> +        <div>
this div is unnecessary

2023-06-30 00:53 UTC, bowenzhu1 commented on frontend/src/components/pages/CaseOverview.tsx
> +      <Flex pt="10" mt="-7">
i think negative margins is generally not a good practice or at least not typically used, is there another way we can format this

2023-06-30 00:53 UTC, bowenzhu1 commented on frontend/src/components/pages/CaseOverview.tsx
> +          <b color={colors.black.default} style={{ fontSize: "12px" }}>
we should use the <Text> component since we're using ChakraUI. Using framework components helps make things consistent instead of using native html

2023-06-30 00:53 UTC, bowenzhu1 commented on frontend/src/components/pages/CaseOverview.tsx
> +          <div
similar comment here to use framework components instead of native <divs> , we should use <Box> or <Flex> or something instead

2023-06-30 00:53 UTC, bowenzhu1 commented on frontend/src/components/pages/CaseOverview.tsx
> +      <div style={{ paddingBottom: "100px" }}>
i dont think we need this div either, could probbably apply the padding to the Flex component right below this

2023-06-30 00:53 UTC, bowenzhu1 commented on frontend/src/components/pages/CaseOverview.tsx
> +              <h1 style={{ fontSize: "23px", fontWeight: 600 }}>Children</h1>
should use Text or Header here as well

2023-06-30 00:53 UTC, bowenzhu1 commented on frontend/src/components/pages/CaseOverview.tsx
> +              <b style={{ fontSize: "20px", fontWeight: 500 }}>
similar comment here as the above, and should be applied for the rest of the file 
- use Framework components instead of native <divs> and html components like <b> <p>
- try to avoid having unnecessary/wrapper components/divs
- use existing styles for components if you can for consistency instead of manually defining CSS

2023-06-30 01:00 UTC, odis43 commented on frontend/src/components/intake/CaseOverviewFooter.tsx
> +        height="38px"
done

2023-06-30 01:02 UTC, odis43 commented on frontend/src/components/intake/CaseOverviewFooter.tsx
> +        <div style={{ paddingRight: "10px" }}>
hmm, i have the padding there to have between the icon and the text Generate Report, removing it brings the icon and the text together with no whitespace

2023-06-30 01:14 UTC, odis43 commented on frontend/src/components/intake/CaseOverviewFooter.tsx
> +      <Box flex="1" /> {/* Spacer element */}
resolved

2023-06-30 02:32 UTC, odis43 commented on frontend/src/components/pages/CaseOverview.tsx
> +      <Flex pt="10" mt="-7">
resolved

2023-06-30 02:38 UTC, odis43 commented on frontend/src/components/pages/CaseOverview.tsx
> +        <div>
removing the div changes the formatting, should i still remove?

2023-06-30 02:41 UTC, odis43 commented on frontend/src/components/pages/CaseOverview.tsx
> +      <div style={{ paddingBottom: "100px" }}>
resolved

2023-06-30 02:43 UTC, odis43 commented on frontend/src/components/pages/CaseOverview.tsx
> +              <h1 style={{ fontSize: "23px", fontWeight: 600 }}>Children</h1>
resolved

2023-06-30 02:47 UTC, odis43 commented on frontend/src/components/pages/CaseOverview.tsx
> +          <b color={colors.black.default} style={{ fontSize: "12px" }}>
resolved

2023-06-30 02:47 UTC, odis43 commented on frontend/src/components/pages/CaseOverview.tsx
> +          <div
resolved

2023-07-07 02:20 UTC, bowenzhu1 approved these changes

2023-07-07 02:20 UTC, merged