Jackie/link case cards w status modal
uwblueprint/childrens-aid-society pull request #188
Opened 2023-06-28 17:19 UTC by jacque1ine

## Notion ticket link

[Link Case Cards with Case Status modal](https://www.notion.so/uwblueprintexecs/Link-Case-Cards-with-Case-Status-modal-4bc9b86f4b2b499db11595f7164d52f7?pvs=4)

## Implementation description
* Implemented logic so that when you click on case card, it opens case status modal
* Removed Test Status Modal button on Home Page
* Refactored code so that instead of "CaseTitle" it is now called caseId so that when we connect to backend, we can just pass caseId into the permanent delete modal

## Steps to test
1. Click on Case Card 
2. verify case status modal opens 
3. verify that the id on the modal matches id of card that you click on 
4. verify that you can open permanent delete modal

## What should reviewers focus on?
* 

## Checklist
- [x] My PR name is descriptive and in imperative tense
- [x] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [x] I have run the appropriate linter(s)
- [x} I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2023-06-30 01:54 UTC, jess94yng requested changes

2023-06-30 01:54 UTC, jess94yng commented on frontend/src/components/dashboard/CaseCard.tsx
> +        status="ARCHIVED"
This should be implemented dynamically - the status should reflect the actual status of the case card

2023-06-30 13:03 UTC, jacque1ine commented on frontend/src/components/dashboard/CaseCard.tsx
> +        status="ARCHIVED"
@jess94yng @bowenzhu1 I just changed it so that the default value of the "case tag" in the status modal w is the same as the status case tag that shows on the case card component. Did you want me to change is so that if you change the status in the dropdown in the status modal, it will move the card to another section?

2023-07-01 23:39 UTC, bowenzhu1 commented on frontend/src/components/dashboard/CaseCard.tsx
> +        status="ARCHIVED"
this is good!

2023-07-01 23:40 UTC, bowenzhu1 approved these changes
lgtm!

2023-07-02 06:20 UTC, merged