Kevin y/archive case action and flow
uwblueprint/childrens-aid-society pull request #189
Opened 2023-06-29 03:46 UTC by kevinasian122

## Notion ticket link

[Archive Case Action and Flow](https://www.notion.so/uwblueprintexecs/134e1f159caa4f73939d11a700c325ad?v=39cf7d5a98384eb9af2bff2265d0ac8a&p=d73085e0a8f4418c8670afdb2b976a29&pm=s)

## Implementation description
* new modal thats toggled by button on homepage
* added put request to intakeAPIClient file and used it to call the put route

## Steps to test
1.

## What should reviewers focus on?
* 

## Checklist
- [x] My PR name is descriptive and in imperative tense
- [x] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [x] I have run the appropriate linter(s)
- [x] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2023-06-30 02:04 UTC, jess94yng requested changes

2023-06-30 02:04 UTC, jess94yng commented on frontend/src/components/dashboard/ArchiveCaseModal.tsx
> +      onClick={archiveCase}
I would add the action of closing the archive modal + going back to main dashboard when user clicks on archive button

2023-07-06 23:17 UTC, bowenzhu1 reviewed
i'm fine w merging this once jessica approves. one q: why are we using `Record<string, string>` for the changedData ?

2023-07-06 23:29 UTC, kevinasian122 commented
> i'm fine w merging this once jessica approves. one q: why are we using `Record<string, string>` for the changedData ?

Umm I think I just couldn't find a proper type that worked so I just went with this LOL

2023-07-14 02:08 UTC, bowenzhu1 approved these changes

2023-07-14 02:28 UTC, merged