Added functionality to clear page button in StatusModal: removes content when clicked
uwblueprint/childrens-aid-society pull request #190
Opened 2023-06-29 20:26 UTC by odis43

## Notion ticket link

[Change Status Modal Clear Page Button](https://www.notion.so/uwblueprintexecs/Change-Status-Modal-Clear-Page-Button-897c498e602a475e93c96e75e95558c7?pvs=4)

## Implementation description
* When there is content in the custom input (meeting notes and worker name), the clear page button will appear
* When clicked, the aforementioned information will be deleted.
* When deleted, the clear page button will also be unloaded 

## Steps to test
1. Check if above functionality works.

## What should reviewers focus on?
* Functionality of the button

## Checklist
- [ x ] My PR name is descriptive and in imperative tense
- [ x  ] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [x  ] I have run the appropriate linter(s)
- [x ] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2023-07-02 16:40 UTC, bowenzhu1 requested changes
some code changes needed, but otherwise implementation is good!

2023-07-02 16:40 UTC, bowenzhu1 commented on frontend/src/components/common/ModalComponent.tsx
> +  meetingNotes,
we shouldnt pass in use case specific props like these to a generic component. 

instead you can pass in `showClearButton`, and when you call ModalComponent in StatusModal, you can pass in the logic you've defined there for `const shouldShowClearButton = meetingNotes !== "" || workerName !== "";`

2023-07-02 16:40 UTC, bowenzhu1 commented on frontend/src/components/dashboard/StatusModal.tsx
> +  const hasAdditionalNotesOrWorkerName =
what's this prop for ? can we remove it if its not used

2023-07-02 16:40 UTC, bowenzhu1 commented on frontend/src/components/dashboard/StatusModal.tsx
> +import { worker } from "cluster";
make sure to check your imports to remove anything added that's not actually being used

2023-07-02 16:43 UTC, jess94yng approved these changes

2023-07-10 20:03 UTC, bowenzhu1 requested changes
need to revert the files relating to case overview in this PR? don't think those changes should be here

2023-07-15 03:30 UTC, bowenzhu1 requested changes
this is super minor, but let's revert the naming of the case overview page back to CASEOVERVIEW_PAGE instead of CASE_OVERVIEW

2023-07-30 01:44 UTC, bowenzhu1 approved these changes
approving and merging

2023-07-30 01:44 UTC, merged