Sohail/view all cases frame
uwblueprint/childrens-aid-society pull request #196
Opened 2023-07-07 00:36 UTC by SohailSayed

## Notion ticket link

[Main Dashboard View All Cases Frame](https://www.notion.so/uwblueprintexecs/Main-Dashboard-View-All-Cases-Frame-59c9aa4ca2a04b20a1358ad7bf9793e7)

## Implementation description
* Create new cases page, display grid of specific type of cases, filtered by query params in URL
* Organize and display case cards in new FilteredCaseDisplay component
* Use empty "filler" box to occupy space when row has less than 4 cases

## Steps to test
1. Direct yourself to the cases page by either clicking on one of the "View All" buttons on Homepage, or typing the URL directly (example http://localhost:3000/cases?status=active)

![image](https://github.com/uwblueprint/childrens-aid-society/assets/44615627/585c8f25-87d6-4a12-88f9-0d8b28cef045)
![image](https://github.com/uwblueprint/childrens-aid-society/assets/44615627/2fec9baf-f61e-480f-a9d5-42497591df9a)

2. Cases should be centered on the page in a grid with 4 cards per row, with the header and back arrow aligned with the leftmost case

## What should reviewers focus on?
* Ensuring spacing issues don't pop up (especially on smaller laptop screen sizes)
* I'd like a second opinion on my current implementation for when there are no cases (can be viewed at http://localhost:3000/cases?status=submitted)

## Checklist
- [x] My PR name is descriptive and in imperative tense
- [x] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [x] I have run the appropriate linter(s)
- [x] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2023-07-09 15:33 UTC, bowenzhu1 requested changes
For the empty state, we shouldn't show the load more button.

Also, not a hard requirement, but could we try making it so that the container wraps when the window is super small, instead of overflowing off the screen. We might be able to use a <Flex> in CasePage to wrap the FilteredCaseSections for this. <img width="957" alt="Screenshot 2023-07-09 at 11 27 28 AM" src="https://github.com/uwblueprint/childrens-aid-society/assets/43287170/bb0d351c-633f-4bb8-bc28-0cffcfda323c">

on the flipside, the container seems to spill if the window is really big as well: 
<img width="1308" alt="Screenshot 2023-07-09 at 11 29 18 AM" src="https://github.com/uwblueprint/childrens-aid-society/assets/43287170/472055fe-5f12-47dc-8e30-3b35f96eccbc">

2023-07-09 15:33 UTC, bowenzhu1 commented on frontend/src/components/common/FilteredCaseDisplay.tsx
> +  for (let i = 0; i < numberOfRows; i += 1) {
this works, but it's a pretty hacky solution. Maybe if we set the Flex justifyContent to be flex-start, then we don't need the additional filler boxes

2023-07-09 15:33 UTC, bowenzhu1 commented on frontend/src/components/pages/CasesPage.tsx
> +      <Flex justifyContent="center" py="45px">
shouldnt show this if cases[status] is empty, could conditionally check that

2023-07-16 16:52 UTC, SohailSayed commented on frontend/src/components/pages/CasesPage.tsx
> +      <Flex justifyContent="center" py="45px">
Just pushed some changes:



> shouldnt show this if cases[status] is empty, could conditionally check that

Load more cases button doesn't show when cases[status] is empty now

> this works, but it's a pretty hacky solution. Maybe if we set the Flex justifyContent to be flex-start, then we don't need the additional filler boxes

No longer using empty case cards/fillers 

>on the flipside, the container seems to spill if the window is really big as well:

This should also be fixed

>Also, not a hard requirement, but could we try making it so that the container wraps when the window is super small, instead of overflowing off the screen. We might be able to use a in CasePage to wrap the FilteredCaseSections for this.

It'll be hard to implement wrapping on the cards since each row (which can have up to 4 cards) is a separate flex container. I could try to implement it so that if the screen size is below a certain size, it switches from showing 4 cards per row to 2 cards per row. Is that worth trying?

2023-07-16 17:00 UTC, bowenzhu1 approved these changes

2023-07-17 21:23 UTC, merged