Kevin y/implement visit cadence model and service
uwblueprint/childrens-aid-society pull request #200
Opened 2023-07-23 15:57 UTC by kevinasian122

## Notion ticket link

[Implement visit cadence model and service](https://www.notion.so/uwblueprintexecs/134e1f159caa4f73939d11a700c325ad?v=39cf7d5a98384eb9af2bff2265d0ac8a&p=4c7326434add43c881cab75ee547c277&pm=s)

## Implementation description
* made functions and routes for get, post, delete, put, and get by intake id
* intake and child should be one-to-many with visit_cadence, and visit_cadence is one-to-one with caregiver
* updated intake, child, and caregiver tables as well

## Steps to test
1. test routes for create, get, update, and delete with required fields, include id as params
2. 
![image](https://github.com/uwblueprint/childrens-aid-society/assets/70108329/aae566e2-d099-437d-87fa-85dd31e2e5f3)

## What should reviewers focus on?
* 

## Checklist
- [x] My PR name is descriptive and in imperative tense
- [x] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [x] I have run the appropriate linter(s)
- [x] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2023-07-30 05:04 UTC, bowenzhu1 requested changes
some minor questions, overall it looks good! Can you make a new Notion page under Engineering, similar to these ones:
https://www.notion.so/uwblueprintexecs/Visits-Frontend-Backend-0390403779eb4231b505430250565e80?pvs=25
https://www.notion.so/uwblueprintexecs/Intake-Frontend-Backend-b771b1d282974532b97e4d2d233e9144

The page should basically be like the VisitCadenceDTO, just recording what the data/json should look like.

lmk once you're done that and I'll glance over it to check - i'll also still be pulling this branch to my local and testing the endpoints with my postman. amazing work thanks!!

2023-07-30 05:04 UTC, bowenzhu1 commented on backend/python/app/services/interfaces/visit_cadence_service.py
> +        :type cadence_id: int
add updated_data param

2023-07-30 15:23 UTC, kevinasian122 commented on backend/python/app/models/intake.py
> -    goals = db.relationship("Goal", secondary=intakes_goals)
Oh I saw that there were duplicate concerns and goals underneath so I removed this when I was trying to figure out what was causing errors and forgot about it, should there be duplicate goals and concerns?

2023-08-20 15:02 UTC, bowenzhu1 approved these changes
nice work! a few small changes + make sure you lint

2023-08-20 15:02 UTC, bowenzhu1 commented on backend/python/app/models/visit_cadence.py
> +    "wednesday",
capitalize this

2023-08-20 15:02 UTC, bowenzhu1 commented on backend/python/app/models/visit_cadence.py
> +        db.Integer, db.ForeignKey("caregivers.id", ondelete="CASCADE"), nullable=True
updated decision from what I previously said: can we switch this so that Caregiver is not nullable, and Child is nullable?

2023-09-01 15:47 UTC, merged