Implement visit component skeleton
uwblueprint/childrens-aid-society pull request #202
Opened 2023-08-18 01:58 UTC by kevinasian122

## Notion ticket link

[Visit log page initial route and template](https://www.notion.so/uwblueprintexecs/134e1f159caa4f73939d11a700c325ad?v=39cf7d5a98384eb9af2bff2265d0ac8a&p=6700fc6233244b17b864eda9c3bc85d3&pm=s)

## Implementation description
* just the skeleton of the page and params gotten from the link

## Steps to test
1.

## What should reviewers focus on?
* 

## Checklist
- [x] My PR name is descriptive and in imperative tense
- [x] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [x] I have run the appropriate linter(s)
- [x] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2023-08-20 15:28 UTC, bowenzhu1 requested changes
small comments

2023-08-20 15:28 UTC, bowenzhu1 commented on frontend/src/components/pages/VisitPage.tsx
> +            <Button variant="primary" width="fit-content">
this shouldn't actually have the button styling at all times.

The designs highlights it because it was clicked, but otherwise we should just have this be normal style for now

2023-08-20 15:28 UTC, bowenzhu1 commented on frontend/src/components/pages/VisitPage.tsx
> +          <Box
This section should take up more of the width relative to the left side box. Refer to the designs to change the formatting/spacing

2023-08-20 15:28 UTC, bowenzhu1 commented on frontend/src/components/pages/VisitPage.tsx
> +  // url is /visit/caseId/visitId
do we need these comments here?

2023-10-09 00:15 UTC, Ezzhingy commented on frontend/src/components/pages/VisitPage.tsx
> +              <ArrowLeft /> Save and Exit {/* TODO implement save and exit */}
nit: wrap this in a button component with empty onclick

2023-10-09 00:16 UTC, Ezzhingy approved these changes
lgtm, left a small optional nit, but solid overall 😎

2023-10-15 18:13 UTC, merged