Created daytime_contacts model
uwblueprint/childrens-aid-society pull request #23
Opened 2022-06-12 16:26 UTC by Het7

## Notion ticket link

Create daytime_contacts model](https://www.notion.so/uwblueprintexecs/Create-daytime_contacts-model-b49208767f4d4559b5da583f9821a6e5)

## Implementation description
* Created a daytime_contacts model based on the schema provided in the ticket

## Checklist
- [x] My PR name is descriptive and in imperative tense
- [x] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [x] I have run the appropriate linter(s)
- [x] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2022-06-12 19:59 UTC, jennchenn requested changes
i don't see your migration here! do you mind generating it first and then re-requesting review?

2022-06-12 19:59 UTC, jennchenn commented on backend/python/app/models/daytime_contacts.py
> +        # define the entities table
nit: remove these comments

2022-06-17 17:31 UTC, Het7 commented
> i don't see your migration here! do you mind generating it first and then re-requesting review?

Done!

2022-06-18 03:46 UTC, jennchenn requested changes
some minor changes - please check that you can run `flask db upgrade && flask db downgrade && flask db upgrade` without issue once you make the changes!

2022-06-18 03:46 UTC, jennchenn commented on backend/python/migrations/versions/4dfecb9b3a37_daytime_contacts.py
> +    # ### end Alembic commands ###
add:
`op.execute("DROP TYPE daytime_contacts_type;")`

2022-06-18 03:46 UTC, jennchenn commented on backend/python/migrations/versions/4dfecb9b3a37_daytime_contacts.py
> +            sa.Enum("School", "Daycare", name="daytime_contact_enum"),
nit: rename
```suggestion
            sa.Enum("School", "Daycare", name="daytime_contacts_type"),
```

2022-06-19 15:12 UTC, Het7 commented
> some minor changes - please check that you can run `flask db upgrade && flask db downgrade && flask db upgrade` without issue once you make the changes!

Yup I'm able to run it without any issues!

2022-06-19 16:07 UTC, jennchenn commented on backend/python/app/models/daytime_contacts.py
> +class daytime_contacts(db.Model):
```suggestion
class DaytimeContact(db.Model):
```

2022-06-19 16:50 UTC, jennchenn approved these changes
:shipit:

2022-06-19 16:50 UTC, merged