Created services to allow creation of new address
uwblueprint/childrens-aid-society pull request #28
Opened 2022-06-13 22:36 UTC by hamza-yusuff

## Notion ticket link

[Create Service to add new address](https://www.notion.so/uwblueprintexecs/Create-service-to-add-new-address-350083b689fd47e6998d4b65d82d4786)

## Implementation description
* Created class, and the associated method to allow creation of a new address record in the db when a CreateAddressDTO is passed to the method. AddressDTO is returned if the function is successful otherwise exception is raised.
* Added corresponding DTO classes with validation methods.
* Added tests to verify functionality

## Steps to test
1) Upgrade your database docker exec -it cas_py_backend /bin/bash -c "flask db upgrade"
2) Run tests: docker exec -it cas_py_backend /bin/bash -c "pip install -e . && pytest"
3) Verify that all of the tests pass

## What should reviewers focus on?
* Do all the tests pass

## Checklist
- [x] My PR name is descriptive and in imperative tense
- [x] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [x] I have run the appropriate linter(s)
- [x] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2022-06-15 04:11 UTC, jennchenn requested changes
nice work thinking up some unique test cases!!

added some thoughts + suggestions for potential refactors/testing improvements

2022-06-15 04:11 UTC, jennchenn commented on backend/python/tests/functional/test_address_service.py
> +    test_address_service = AddressService(current_app.logger)
similar to how it's done in the other files right now, can you move this out into a fixture at the top of the file?
https://github.com/uwblueprint/childrens-aid-society/blob/0258555311c572b1d58c18becba0bb5d4a8d4667/backend/python/tests/functional/test_user_service.py#L24-L28

2022-06-15 04:11 UTC, jennchenn commented on backend/python/tests/functional/test_address_service.py
> +            city="",
this is an interesting case - we actually _don't_ want empty strings for `street_address`, `city`, `postal_code`
your validation currently doesn't handle this, but at the very least i don't think we should include this under the valid cases

2022-06-15 04:11 UTC, jennchenn commented on backend/python/tests/functional/test_address_service.py
> +def test_create_address_success():
can you actually separate each of these into their own tests rather than running them in one batch (this applies for both the valid and invalid test cases)?

in the case of errors, it'll make it easier to pinpoint which test case is causing the failure if we have them isolated in their own tests (additionally this separates out the testing so one failed test case doesn't cause all of them to not be run)

as a bonus, if we implement test code coverage reporting, having the test cases separated out will be useful too!

2022-06-15 04:11 UTC, jennchenn commented on backend/python/tests/functional/test_address_service.py
> +        # normal case
for the normal case, you could also validate the fields in the return object match the input (not necessary for all the test cases, but maybe just one)

2022-06-15 04:11 UTC, jennchenn commented on backend/python/tests/functional/test_address_service.py
> +    ]
since `latitude` and `longitude` are the only non-nullable fields right now, can you add a test case where neither are provided to ensure it works?

2022-06-15 04:11 UTC, jennchenn commented on backend/python/tests/functional/test_address_service.py
> +def test_create_address_invalid_field_fails():
since you added validation for an empty address being passed to the service, you can add that test case here!

```
with pytest.raises(Exception):
     test_address_service.create_address(None)
```

2022-06-17 03:21 UTC, hamza-yusuff commented on backend/python/app/resources/address_dto.py
> +        self.id = id
Done!

2022-06-17 03:22 UTC, hamza-yusuff commented on backend/python/app/resources/address_dto.py
> +        self.longitude = kwargs.get("longitude")
Made the changes!

2022-06-17 03:27 UTC, hamza-yusuff commented on backend/python/tests/functional/test_address_service.py
> +def test_create_address_success():
Just a bit confused on this. Do i separate the cases into their own function? for example functions like - test_create_address_success_normal_case(), test_create_address_success_boundary_case(), test_create_address_success_precision_case() - for each test case?

2022-06-17 03:40 UTC, hamza-yusuff commented on backend/python/app/services/implementations/address_service.py
> +            if address:
Yess, changed the code to log the error only once, also added checks to see if it is of type CreateDTO or not

2022-06-18 03:49 UTC, jennchenn commented on backend/python/tests/functional/test_address_service.py
> +def test_create_address_success():
Yes - you can test more than once for normal case, but I think this makes it clearer when we analyze the test results after the tests are run (i.e. instead of seeing `test_create_address_success` fail and having to check which of the specific cases caused it to fail, we can pinpoint that it's a boundary case or precision, etc. that caused the failure)

^ you don't have to separate it out if it seems pretty similar to you, but i think if you have different conditions/things you're testing, would be good to separate it out

2022-06-19 16:28 UTC, hamza-yusuff commented on backend/python/tests/functional/test_address_service.py
> +    test_address_service = AddressService(current_app.logger)
Done!

2022-06-19 16:31 UTC, hamza-yusuff commented on backend/python/tests/functional/test_address_service.py
> +def test_create_address_success():
I created tow separate class for the normal and invalid cases, and then put the test cases as methods for the classes to keep the cases grouped according to what they test essentially.

2022-06-19 16:32 UTC, hamza-yusuff commented on backend/python/tests/functional/test_address_service.py
> +        # normal case
Yess I have put a test case which validates the return object's field with the input's

2022-06-19 16:32 UTC, hamza-yusuff commented on backend/python/tests/functional/test_address_service.py
> +    ]
Yeah added this well

2022-06-19 18:46 UTC, jennchenn approved these changes
i think this looks good!! nice 🥳

2022-06-20 02:04 UTC, merged