Add method get_all_transportation_methods
uwblueprint/childrens-aid-society pull request #31
Opened 2022-06-22 20:22 UTC by thrvg

## Notion ticket link

[Get all transportation methods](https://www.notion.so/uwblueprintexecs/134e1f159caa4f73939d11a700c325ad?v=39cf7d5a98384eb9af2bff2265d0ac8a&p=dabf303df3f842889bfaa96c68ff1f0d)

## Implementation description
* Modified transportation_method_service implementation and interface to add method get_transportation_methods
* Used TransportationMethod.query to get data and modified the data with to_dict() 
* Added error checking
* Added tests 

## Steps to test
1. Run tests
2. Verify code changes in 3 files

## What should reviewers focus on?
* Run the tests. One test should fail (empty db) as I was not sure how to implement that test.

## Checklist
- [x] My PR name is descriptive and in imperative tense
- [x] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [x] I have run the appropriate linter(s)
- [x] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2022-06-23 01:02 UTC, jennchenn requested changes
looking good so far! we can discuss how to best do the tests

2022-06-24 16:40 UTC, thrvg commented
Hi Jenn!

Made the changes. Please let me know if apart from the tests written in `test_get_transportation_method_success(..)`, everything else looks okay. :)

We could discuss the test implementation on Sunday.

2022-06-30 02:29 UTC, jennchenn commented on backend/python/tests/functional/test_transport_method_service.py
> +    assert len(transportation_methods) == 0
thoughts on something like this instead? it should do the same checks but i think this is a bit more understandable (feel free to modify though!)

also i don't think we need to comment exactly what we're doing unless it's really unclear (e.g. you could add a comment like `Checking return matches expected transportation methods`, but other ones i don't think are necessary)

```suggestion
    assert type(res) == list
    assert len(res) == 3
    assert all(type(item) == TransportationMethodDTO for item in res)

    transportation_methods_db = [
        entry["transportation_method"] for entry in DEFAULT_TRANSPORTATION_METHODS
    ]
    transportation_methods_res = [item.transportation_method for item in res]
    assert set(transportation_methods_db) == set(transportation_methods_res)

```

2022-07-02 18:38 UTC, thrvg commented on backend/python/tests/functional/test_transport_method_service.py
> +    assert len(transportation_methods) == 0
Yes, definitely increases readability! Will commit the changes.

2022-07-03 15:29 UTC, jennchenn approved these changes
nice work!

2022-07-03 15:29 UTC, jennchenn commented on backend/python/tests/functional/test_transport_method_service.py
> +    assert len(res) == 3
nit
```suggestion
    assert len(res) == len(DEFAULT_TRANSPORTATION_METHODS)
```

2022-07-07 00:44 UTC, merged