Updated alembic.inic
uwblueprint/childrens-aid-society pull request #34
Opened 2022-06-23 02:12 UTC by hamza-yusuff

Updated alembic.inic file to generate migration version file with a sequential naming.

## Notion ticket link

[Update Alembic version naming convention](https://www.notion.so/uwblueprintexecs/Update-Alembic-version-naming-convention-8ca2f3719f284bc49443dbb16aa2971e)

## Implementation description
* Changed the file_template variable in the file alembic.inic such that it creates migration file versions with this naming format - YYYYMMDD-description

## Steps to test
1. Make changes to the schema and run migrations OR downgrade to base migration, then upgrade and finally generate a migration file
2. Verify that the migration file generated has naming of this format -> YYYYMMDD-description

## What should reviewers focus on?
* Does the migration file follow the specified format for it's naming?

## Checklist
- [X] My PR name is descriptive and in imperative tense
- [X] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [X] I have run the appropriate linter(s)
- [X] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2022-06-23 02:16 UTC, jennchenn requested changes
tested and it works!

nit: can you rename PR title to something a bit more descriptive (e.g. `Add date to migration file name`)?

2022-06-23 02:16 UTC, jennchenn commented on backend/python/migrations/alembic.ini
> +file_template = %%(year)d_%%(month).2d_%%(day).2d-%%(slug)s
can you add `%%(rev)s` to the name (before the slug maybe)

2022-06-23 16:17 UTC, hamza-yusuff commented on backend/python/migrations/alembic.ini
> +file_template = %%(year)d_%%(month).2d_%%(day).2d-%%(slug)s
Actually, the rev_id was there but then I thought would that cause the migration version files to not be in sequence? as in would that affect the sorting?

2022-06-23 21:33 UTC, jennchenn commented on backend/python/migrations/alembic.ini
> +file_template = %%(year)d_%%(month).2d_%%(day).2d-%%(slug)s
If you do `<date>_<rev ID>_<slug>` it should remain ordered

2022-06-24 06:16 UTC, hamza-yusuff commented on backend/python/migrations/alembic.ini
> +file_template = %%(year)d_%%(month).2d_%%(day).2d-%%(slug)s
Oh alright, having the changes done that way then.

2022-06-24 21:29 UTC, jennchenn approved these changes
one formatting nit; otherwise looks good, nice!

2022-06-24 21:29 UTC, jennchenn commented on backend/python/migrations/alembic.ini
> +file_template = %%(year)d_%%(month).2d_%%(day).2d-%%(rev)s_%%(slug)s
```suggestion
file_template = %%(year)d-%%(month).2d-%%(day).2d_%%(rev)s_%%(slug)s
```

2022-06-24 22:47 UTC, merged