Added script to generate local_test_coverage_report
uwblueprint/childrens-aid-society pull request #42
Opened 2022-07-03 15:59 UTC by hamza-yusuff

## Notion ticket link

[Setup local code coverage reporting tools](https://www.notion.so/uwblueprintexecs/134e1f159caa4f73939d11a700c325ad?v=39cf7d5a98384eb9af2bff2265d0ac8a&p=861abcaffb604cd08d916638a41fd612)

## Implementation description
* Added a python script to run python coverage module over all the tests

## Steps to test
1. Run the command ``` docker exec -it cas_py_backend /bin/bash -c "python /app/tests/coverage.py"```

## What should reviewers focus on?
* A report like this should be generated --> 
( Note : the actual report is much bigger )

<img width="805" alt="Screenshot 2022-07-03 at 11 55 50 AM" src="https://user-images.githubusercontent.com/63330003/177047467-a9581364-5712-4384-9a63-565b3cbf6890.png">

<img width="770" alt="Screenshot 2022-07-03 at 11 57 26 AM" src="https://user-images.githubusercontent.com/63330003/177047525-884bbb74-6b2f-408a-a6da-25055461e27b.png">
<img width="692" alt="Screenshot 2022-07-03 at 11 57 41 AM" src="https://user-images.githubusercontent.com/63330003/177047539-227cd4f1-a1f4-471d-876f-7b16e3de62ae.png">

## Checklist
- [X] My PR name is descriptive and in imperative tense
- [X] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [X] I have run the appropriate linter(s)
- [X] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2022-07-03 17:29 UTC, jennchenn requested changes
exciting stuff!!

1. can you make this a shell script instead of importing `os`?
2. can you add `*.coverage` files to `.gitignore`
3. can you add some instructions for how to run the coverage script in the readme (add a subsection under the running tests section)

2022-07-07 03:16 UTC, jennchenn reviewed
looking good! few comments

I also had to add `coverage` to my `requirements.txt` file - can you double check whether or not you needed to do this and make changes as appropriate?

```
coverage==6.4.1
```

2022-07-07 03:16 UTC, jennchenn commented on .gitignore
> +*.coverage
I think you'll also have to do a `git rm --cached *.coverage` in your terminal to ensure the committed `.coverage` files are ignored in the future

2022-07-07 21:16 UTC, hamza-yusuff commented on .gitignore
> +*.coverage
Thanks, I did this.

2022-07-10 15:03 UTC, jennchenn commented on .gitignore
> +*.coverage
i think you'll have to commit the deleted files! i still see it in commit

2022-07-10 15:26 UTC, jennchenn reviewed
the command didn't output the report for me as is for some reason (i tested with a newly built container) - commented the changes i made to make it work!

2022-07-10 15:26 UTC, jennchenn commented on README.md
> + docker exec -it cas_py_backend /bin/bash -c "bash /app/tests/coverage.sh"
```suggestion
 docker exec -it cas_py_backend /bin/bash -c "./tests/coverage.sh"
```

2022-07-10 15:26 UTC, jennchenn commented on backend/python/tests/coverage.sh
> +#!/bin/sh
to stay consistent, let's use bash instead
```suggestion
#!/bin/bash
```

2022-07-10 15:26 UTC, jennchenn commented on backend/python/tests/coverage.sh
> +#!/bin/sh
you may have to toggle the `CRLF/LF` if you get a bad interpreter message:
![image](https://user-images.githubusercontent.com/32009013/178151246-9d09a2e2-23be-42a7-bf9f-66d3b2e6fe4a.png)

2022-07-10 15:54 UTC, hamza-yusuff commented on .gitignore
> +*.coverage
Deleted the files from the tree. It should be okay i guess

2022-07-12 00:26 UTC, jennchenn reviewed
figured out how to make line endings consistent - can you add this to `.gitattributes`:
```
backend/python/tests/coverage.sh eol=lf
```

and run `git add --renormalize .` and commit?

after this both commands work for me (with / without bash)

2022-07-12 02:18 UTC, jennchenn approved these changes
nit: i would prefer `docker exec -it cas_py_backend /bin/bash -c "./tests/coverage.sh"` if that command works for you as well

will approve now, so just merge when you fix the nit! nice work

2022-07-12 02:18 UTC, jennchenn commented on .gitattributes
> +backend/python/tests/coverage.sh eol=lf
nit: newline

2022-07-12 02:39 UTC, merged