Add method get_all_branches
uwblueprint/childrens-aid-society pull request #44
Opened 2022-07-06 21:37 UTC by Het7

## Notion ticket link

[Get all branches](https://www.notion.so/uwblueprintexecs/Get-all-branches-775048333d5642c4b2f9194287bd6bb2)

## Implementation description
* Modified get_branch implementation and interface to add method get_branches

## Checklist
- [x] My PR name is descriptive and in imperative tense
- [x] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [x] I have run the appropriate linter(s)
- [x] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2022-07-07 01:37 UTC, andrew-y-ma requested changes

2022-07-07 01:37 UTC, andrew-y-ma commented on backend/python/app/services/implementations/branch_service.py
> +from unittest import result
nit: I think this can be removed

2022-07-07 01:37 UTC, andrew-y-ma commented on backend/python/app/services/implementations/branch_service.py
> +
I think you could add a test_get_branches_success function. It would look similar to the following code but with access type swapped out for branches!

```
def test_get_access_types_success(access_type_service):
    res = access_type_service.get_access_types()
    assert type(res) == list
    assert len(res) == len(DEFAULT_ACCESS_TYPES)
    assert all(type(item) == AccessTypeDTO for item in res)
    access_types_db = [entry["access_type"] for entry in DEFAULT_ACCESS_TYPES]
    access_type_res = [item.access_type for item in res]
    assert set(access_types_db) == set(access_type_res)
```

2022-07-07 03:22 UTC, jennchenn requested changes
few nits and +1 to Andrew's comment about testing!

2022-07-07 03:22 UTC, jennchenn commented on backend/python/app/services/interfaces/branch_service.py
> +        """Add branch to DB and return the id
nit:
```suggestion
        """Fetches all branches in the database
```

2022-07-07 03:22 UTC, jennchenn commented on backend/python/app/services/interfaces/branch_service.py
> +        :rtype: list
nit:
```suggestion
        :rtype: List of BranchDTO
```

2022-07-07 03:22 UTC, jennchenn commented on backend/python/app/services/interfaces/branch_service.py
> +        :param branch: None
nit: remove

2022-07-07 03:24 UTC, jennchenn commented on backend/python/app/services/implementations/branch_service.py
> +
you can find the test files here!:
https://github.com/uwblueprint/childrens-aid-society/blob/7ba47184164f9234d4f1333dd2fe7c8c568014bb/backend/python/tests/unit/test_access_type_service.py#L60-L67

https://github.com/uwblueprint/childrens-aid-society/blob/7ba47184164f9234d4f1333dd2fe7c8c568014bb/backend/python/tests/functional/test_transport_method_service.py#L61-L70

2022-07-07 05:14 UTC, Het7 commented on backend/python/app/services/interfaces/branch_service.py
> +        :param branch: None
Sorry should I just remove line 25?

2022-07-09 03:56 UTC, Het7 commented on backend/python/app/services/interfaces/branch_service.py
> +        :param branch: None
Yeah it doesn't have a param
I just deleted line 25

2022-07-12 02:05 UTC, jennchenn commented on backend/python/tests/functional/test_get_all_branches_service.py
> +def test_get_branches_success(access_type_service):
can you go through and rename `access_type_service`->`branch_service`

2022-07-12 02:07 UTC, jennchenn commented on backend/python/app/services/implementations/branch_service.py
> +from ...models import branch, db
```suggestion
from ...models import db
```

2022-07-12 02:10 UTC, jennchenn commented on backend/python/tests/functional/test_get_all_branches_service.py
> +def test_get_branches_success(access_type_service):
can you also move this test into `unit/test_branch_service.py` (and move the file to `functional/`

2022-07-12 03:45 UTC, Het7 commented on backend/python/tests/functional/test_get_all_branches_service.py
> +def test_get_branches_success(access_type_service):
Sorry I just want to clarify:
Isn't this file already in `functional/`?
Will this file only consist of the imports (for now) since we're moving the test into `unit/test_branch_service.py`?

2022-07-12 03:51 UTC, jennchenn commented on backend/python/tests/functional/test_get_all_branches_service.py
> +def test_get_branches_success(access_type_service):
two steps to this change:
1. rather than making a new test file, just add your test to [this file](https://github.com/uwblueprint/childrens-aid-society/blob/main/backend/python/tests/unit/test_branch_service.py); delete your test file after this is done
2. move the whole file (`unit/test_branch_service.py`) to `functional/test_branch_service.py`

2022-07-13 01:05 UTC, Het7 commented
Thanks for all the reviews!

2022-07-13 01:06 UTC, jennchenn approved these changes
lgtm! one nit

2022-07-13 01:06 UTC, jennchenn commented on backend/python/tests/functional/test_branch_service.py
> +
nit: remove

2022-07-13 01:09 UTC, Het7 commented on backend/python/tests/functional/test_branch_service.py
> +
Done, nice catch!

2022-07-13 01:13 UTC, merged