Squash Goals and Concerns Tables
uwblueprint/childrens-aid-society pull request #45
Opened 2022-07-07 01:15 UTC by andrew-y-ma

## Notion ticket link
[Condense goals and concerns tables](https://www.notion.so/uwblueprintexecs/Condense-goals-and-concerns-tables-ded314841c9f49f28241e9b686343ed7)

## Implementation description
* Squash familial concerns and child concerns models into one concerns model. Add a concerns_type enum to differentiate between different concerns in the unified concerns model
* Set up concerns_intake table with intake_id and concern_id foreign keys
* Squash long term and short terms goal models into a unified goals model. Add a goals_type enum to differentiate between different goals in the goals model.
* Modify alembic migration file to ensure data is seeded correctly upon db upgrade and db downgrade

## Steps to test
1. Restart your docker containers: docker-compose down --volumes && docker-compose up
2. Exec into the backend container: docker exec -it cas_py_backend /bin/bash
3. Upgrade the database: flask db upgrade -- verify that it works successfully
4. Downgrade and upgrade the database again: flask db downgrade && flask db upgrade -- verify that it works successfully
5. Exec into the db container: docker exec -it cas_db psql -U postgres -d cas
6. Verify that `concerns`, `goals`, and `intakes_concerns` tables are present as shown below. Also verify that old `child_concerns`, `familial_concerns`, `long_term_goals`, and `short_term_goals` tables are not present.
<img width="432" alt="image" src="https://user-images.githubusercontent.com/55464415/177668304-ee575fd1-5ce3-4d2b-be00-576d634f650a.png">
7. Downgrade the database: flask db downgrade. Verify `child_concerns`, `familial_concerns`, `long_term_goals`, and `short_term_goals` tables have been restored.

## What should reviewers focus on?
* concerns_intake table has the correct foreign keys set
* Tables have the correct columns in postgres

## Checklist
- [ ] My PR name is descriptive and in imperative tense
- [ ] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [ ] I have run the appropriate linter(s)
- [ ] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2022-07-07 04:06 UTC, jennchenn requested changes
nice work!! a few questions about some parts of the downgrade but otherwise looks good 🎉

2022-07-07 04:06 UTC, jennchenn commented on backend/python/migrations/versions/2022-07-03_57f14d8ff8bf_condense_goals_and_concerns_models.py
> +        sa.Column("intake_id", sa.INTEGER(), autoincrement=False, nullable=True),
I think we use `sa.Integer()` in other places

2022-07-07 04:06 UTC, jennchenn commented on backend/python/migrations/versions/2022-07-03_57f14d8ff8bf_condense_goals_and_concerns_models.py
> +        sa.Column("goal", sa.VARCHAR(), autoincrement=False, nullable=False),
this can probably be a `sa.String()`

2022-07-07 04:06 UTC, jennchenn commented on backend/python/app/models/concern.py
> +    type = db.Column(type_enum)
can you make this `nullable=False`

2022-07-07 04:06 UTC, jennchenn commented on backend/python/app/models/goal.py
> +    type = db.Column(type_enum)
can you make this `nullable=False`

2022-07-10 15:19 UTC, andrew-y-ma commented on backend/python/migrations/versions/2022-07-03_57f14d8ff8bf_condense_goals_and_concerns_models.py
> +            server_default=sa.text("nextval('familial_concerns_id_seq'::regclass)"),
I believe this was auto generated

2022-07-10 15:20 UTC, andrew-y-ma commented on backend/python/migrations/versions/2022-07-03_57f14d8ff8bf_condense_goals_and_concerns_models.py
> +        sa.Column("intake_id", sa.INTEGER(), autoincrement=False, nullable=True),
Ah alright will change!

2022-07-10 15:22 UTC, andrew-y-ma commented on backend/python/migrations/versions/2022-07-03_57f14d8ff8bf_condense_goals_and_concerns_models.py
> +    op.drop_table("child_concerns")
Yeah changing the order works!

2022-07-10 15:28 UTC, jennchenn commented on backend/python/migrations/versions/2022-07-03_57f14d8ff8bf_condense_goals_and_concerns_models.py
> +            server_default=sa.text("nextval('familial_concerns_id_seq'::regclass)"),
hm i don't think any of the other tables require it to have autoincrementing ID's -- can you check if it's necessary and remove if not? just want to keep things consistent across tables

2022-07-10 15:51 UTC, andrew-y-ma commented on backend/python/migrations/versions/2022-07-03_57f14d8ff8bf_condense_goals_and_concerns_models.py
> +            server_default=sa.text("nextval('familial_concerns_id_seq'::regclass)"),
I can change it to how the goals table were created in the original migration!

2022-07-12 02:11 UTC, jennchenn commented on backend/python/migrations/versions/2022-07-03_57f14d8ff8bf_condense_goals_and_concerns_models.py
> +            server_default=sa.text("nextval('familial_concerns_id_seq'::regclass)"),
i think so! (but again not sure why the autogeneration produced this instead this time, so let me know if you think that'd break anything)

2022-07-13 01:13 UTC, jennchenn approved these changes
looks good!!

2022-07-13 01:30 UTC, merged