Add new caregiver service
uwblueprint/childrens-aid-society pull request #52
Opened 2022-07-20 01:31 UTC by hamza-yusuff

## Notion ticket link

[Add new caregiver](https://www.notion.so/uwblueprintexecs/Add-new-caregiver-dc491e2b05c94e93aaf0f56db9415c3b)

## Implementation description
* Added `Caregiver_DTO` and `CreateCaregiver_DTO`
* Added interface for `Caregiver` service
* Added caregiver services function.

## Steps to test
1. Check if all the tests pass by running - `docker exec -it cas_py_backend /bin/bash -c "pip install -e . && pytest"`

## What should reviewers focus on?
* The valid test cases are yet to be written for the `Caregiver` services because of the different relationships between `Caregiver` model and other existing models. To create a dummy `Caregiver` record for the tests, other dummy models that the `Caregiver` model is associated with needs to created too. Well, that could be done with `pytest fixtures` but for some reason, some weird error shows up.

## Checklist
- [X] My PR name is descriptive and in imperative tense
- [X] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [X] I have run the appropriate linter(s)
- [X] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2022-07-20 02:33 UTC, jennchenn requested changes
left a suggestion on how to fix the tests - try it out and let me know if it works

2022-07-20 02:33 UTC, jennchenn commented on backend/python/app/resources/caregiver_dto.py
> +            error_list.append("The street_address value supplied is not a string.")
```suggestion
            error_list.append("The first name value supplied is not a string.")
```

2022-07-20 02:33 UTC, jennchenn commented on backend/python/tests/functional/test_caregiver_service.py
> +            caregiver_service.create_caregiver(None)
```suggestion
import pytest
from flask import current_app

from app.models import db
from app.models.user import User
from app.models.address import Address
from app.models.caregiver import Caregiver
from app.models.child import Child
from app.models.daytime_contact import DaytimeContact
from app.resources.caregiver_dto import CreateCaregiverDTO
from app.services.implementations.caregiver_service import CaregiverService


@pytest.fixture
def caregiver_service():
    caregiver = CaregiverService(current_app.logger)
    seed_database()
    yield caregiver
    teardown_database()
    Caregiver.query.delete()


DUMMY_USER_DATA = {
    "first_name": "Hamza",
    "last_name": "Yusuff",
    "auth_id": "hbyusuff",
    "role": "Driver",
    "branch": "ALGOMA",
}

DUMMY_ADDRESS_DATA = {
    "street_address": "Lester Street",
    "city": "waterloo",
    "postal_code": "N2L3W6",
}

DUMMY_DAYTIME_CONTACT_DATA = {
    "contact_first_name": "Hamza",
    "contact_last_name": "Yusuff",
    "phone_number": "8790832",
    "type": "SCHOOL",
}

DUMMY_CHILD_DATA = {
    "first_name": "Hamza",
    "last_name": "Yusuff",
    "child_service_worker_id": 1,
    "daytime_contact_id": 1,
    "special_needs": "None",
    "has_kinship_provider": False,
    "has_foster_placement": False,
}


def seed_database():
    new_user = User(**DUMMY_USER_DATA)
    db.session.add(new_user)
    db.session.commit()

    new_address = Address(**DUMMY_ADDRESS_DATA)
    db.session.add(new_address)
    db.session.commit()

    DUMMY_DAYTIME_CONTACT_DATA["address_id"] = new_address.id
    new_daytime_contact = DaytimeContact(**DUMMY_DAYTIME_CONTACT_DATA)
    db.session.add(new_daytime_contact)
    db.session.commit()

    DUMMY_CHILD_DATA["child_service_worker_id"] = new_user.id
    DUMMY_CHILD_DATA["daytime_contact_id"] = new_daytime_contact.id
    new_child = Child(**DUMMY_CHILD_DATA)
    db.session.add(new_child)
    db.session.commit()


def teardown_database():
    Caregiver.query.delete()
    Child.query.delete()
    DaytimeContact.query.delete()
    Address.query.delete()
    User.query.delete()


class TestCreateCaregiverInvalidFails:
    def test_missing_field(self, caregiver_service):
        param = CreateCaregiverDTO(
            type="PROVIDER",
            first_name="Hamza",
            child_id=1,
            relationship_to_child="DAD",
            phone_number="980332434",
        )
        with pytest.raises(Exception):
            caregiver_service.create_caregiver(param)

    def test_empty_input_string(self):
        param = CreateCaregiverDTO(
            type="PROVIDER",
            first_name="Hamza",
            last_name="",
            child_id=1,
            relationship_to_child="DAD",
            phone_number="980332434",
        )
        with pytest.raises(Exception):
            caregiver_service.create_caregiver(param)

    def test_empty_param(self):
        with pytest.raises(Exception):
            caregiver_service.create_caregiver(None)
```

2022-07-20 03:40 UTC, hamza-yusuff commented on backend/python/app/resources/caregiver_dto.py
> +            error_list.append("The street_address value supplied is not a string.")
SORRYY about these mistakes!

2022-07-20 03:54 UTC, hamza-yusuff commented on backend/python/tests/functional/test_caregiver_service.py
> +            caregiver_service.create_caregiver(None)
Yess they do. Actually the invalid test cases were passing with my previous but the problems would arose for the valid cases. I'll let you know quickly if this implementation work for the valid cases.

2022-07-20 03:57 UTC, hamza-yusuff commented on backend/python/app/resources/caregiver_dto.py
> +        child,
I was confused about these two. They have no role, but just kept it to see if they would solve the issue for testing. I'll have them removed. Doesn't look like they have a role.

2022-07-20 03:58 UTC, hamza-yusuff commented on backend/python/app/resources/caregiver_dto.py
> +    def __init__(
Yes making the changes.

2022-07-21 01:56 UTC, jennchenn reviewed
i think this looks good! do you mind removing the `.coverage` file - it should be ignored (can you do `git rm --cached backend/python/.coverage` and push the result again)?

2022-07-21 01:56 UTC, jennchenn commented on backend/python/app/resources/caregiver_dto.py
> +    def validate(self):
is there a specific reason why you skip `is_primary` and `date_of_birth` (I'm assuming you skipped `type`, `relationship_to_child` bc they're enums?)

2022-07-21 02:46 UTC, hamza-yusuff commented on backend/python/app/resources/caregiver_dto.py
> +    def validate(self):
Yes for the `type` and `relationship_to_child`, I skipped them because they are enums. `date_of_birth` gave some weird error before, but I can try again. I thought it was not particularly necessary because the type can only be one type even when entering the record.

2022-07-23 01:33 UTC, jennchenn approved these changes
looks good! nice work

2022-07-23 01:33 UTC, jennchenn commented on backend/python/tests/coverage.sh
> +coverage report
nit: newline

2022-07-23 04:16 UTC, merged