Add method to get and add a goal
uwblueprint/childrens-aid-society pull request #56
Opened 2022-07-21 02:14 UTC by Het7

## Notion ticket link

[Add method to get and add a goal](https://www.notion.so/uwblueprintexecs/Add-method-to-get-and-add-a-goal-5c1d3c9da91743b99c580816d2cb96bc)

## Implementation description
* followed along branches PR

## Checklist
- [x] My PR name is descriptive and in imperative tense
- [x] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [x] I have run the appropriate linter(s)
- [x] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2022-07-23 01:25 UTC, jennchenn requested changes
requesting some changes!

for reference, please take a look at how the goal table is set up here: https://github.com/uwblueprint/childrens-aid-society/blob/main/backend/python/app/models/goal.py and also @thrvg's old PR linked in the comments below!

2022-07-23 01:25 UTC, jennchenn commented on backend/python/app/resources/goal_dto.py
> +        self.goal = bragoalnch.upper()
```suggestion
        self.goal = goal.upper()
```

2022-07-23 01:25 UTC, jennchenn commented on backend/python/app/services/implementations/goal_service.py
> +class GoalService(IGoalService):
@thrvg made some changes to this sort of logic in #48 

for example, take a look at: https://github.com/uwblueprint/childrens-aid-society/blob/main/backend/python/app/services/implementations/transport_method_service.py

2022-07-23 01:25 UTC, jennchenn commented on backend/python/app/services/implementations/goal_service.py
> +    def add_new_goal(self, goal):
this method should accept a `type` parameter as well

2022-07-23 01:25 UTC, jennchenn commented on backend/python/app/resources/goal_dto.py
> +    def __init__(self, goal):
you should add a `type` parameter here

2022-07-23 01:25 UTC, jennchenn commented on backend/python/app/resources/goal_dto.py
> +    def __init__(self, id, goal):
you should add a `type` parameter here

2022-07-23 01:25 UTC, jennchenn commented on backend/python/tests/functional/test_goal_service.py
> +import pytest
these tests don't seem to be passing atm - can you make the above changes, and add in a `type` to these default goals as well?

2022-07-24 16:55 UTC, jennchenn commented on backend/python/app/services/implementations/goal_service.py
> +    def get_goal(self, goal):
do you mind making two separate get methods here: one for `get_short_term_goal` and `get_long_term_goal`

they would essentially look the same as your current get method, but with an added `type=` in the filter

2022-07-25 03:39 UTC, Het7 commented on backend/python/tests/functional/test_goal_service.py
> +import pytest
Yeah for sure! 
Would a goal with `type` look like this:
`{"SHORT_TERM": "Caregiver(s) encourage/allow"}`

2022-07-26 04:07 UTC, jennchenn commented on backend/python/tests/functional/test_goal_service.py
> +import pytest
if you take a look at the model, it should have a `concern` field and a `type` field

/take a look at the migration from Andrew's squash concerns table PR it should have some examples there you can use !!!

2022-07-31 15:26 UTC, Het7 commented on backend/python/app/services/implementations/goal_service.py
> +    def get_goal(self, goal):
Sounds good, I have made the changes!

2022-09-12 17:20 UTC, jennchenn approved these changes

2022-09-12 17:20 UTC, merged