Hamza/update get add methods for concern services
uwblueprint/childrens-aid-society pull request #59
Opened 2022-07-24 21:08 UTC by hamza-yusuff

## Notion ticket link

[Update get/add new familial/child concerns method](https://www.notion.so/uwblueprintexecs/Update-get-add-new-familial-child-concerns-method-980c56eb70bc4447a4c76bba78cd2a7d)

## Implementation description
* Changed implementation pattern for `get` methods to query the single `Concern` table for both `familial` and `child` concerns.  Added optional `type` param for the `get` methods. 
* Updated the `add` method to reference the single `Concern` table. 
* Updated the tests to work properly with the changes.

## Steps to test
1. Run the tests to see if all of them pass.

## What should reviewers focus on?
* Optional `type` param for `get` methods could be made non-optional with only one method for `get`. 

## Checklist
- [X] My PR name is descriptive and in imperative tense
- [X] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [X] I have run the appropriate linter(s)
- [X] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2022-07-27 00:57 UTC, jennchenn requested changes
few questions about the current implementation + some smaller nits!

2022-07-27 00:57 UTC, jennchenn commented on backend/python/app/services/implementations/concern_service.py
> +    def get_familial_concern(self, familial_concern, type=None):
since you have two separated functions here, is the `type` parameter necessary?

i think you can either:
1. keep the two separate functions, remove `type`
2. combine into one get function with the `type` param logic as is

2022-07-27 00:57 UTC, jennchenn commented on backend/python/tests/coverage.py
> +test_coverage_report()
this should be removed

in the future when you make new branches, do you mind checking out from main? / can you delete this file locally if it still exists it has been creeping into all of your recent PRs (this and the `.coverage` file)

2022-07-27 00:57 UTC, jennchenn commented on backend/python/tests/unit/test_concern_service.py
> +def test_get_familial_concern_id_success(concern_service):
nit ```suggestion
def test_get_familial_concern_success(concern_service):
```

2022-07-27 00:57 UTC, jennchenn commented on backend/python/tests/unit/test_concern_service.py
> +def test_get_child_concern_id_success(concern_service):
nit ```suggestion
def test_get_child_concern_success(concern_service):
```

2022-07-27 00:57 UTC, jennchenn commented on backend/python/tests/unit/test_concern_service.py
> +    assert Concern.query.get(res.id).concern == "TERROR"
what's the difference between `test_add_familial_concern` and `test_add_familial_concern_success`?

2022-07-27 00:57 UTC, jennchenn commented on backend/python/tests/unit/test_concern_service.py
> +    assert Concern.query.get(res.id).concern == "TERROR"
same for `child_concern` variant

2022-07-27 03:57 UTC, hamza-yusuff commented on backend/python/app/services/implementations/concern_service.py
> +    def get_familial_concern(self, familial_concern, type=None):
Since, the tests are designed without the `type`, I'll move ahead with the first option.

2022-07-27 03:57 UTC, hamza-yusuff commented on backend/python/tests/coverage.py
> +test_coverage_report()
Yeah I am sorry about this. This somehow manages to creep into the commit. I'll have it removed permanently.

2022-07-28 04:37 UTC, hamza-yusuff commented on backend/python/tests/unit/test_concern_service.py
> +    assert Concern.query.get(res.id).concern == "TERROR"
They just test different types of familial and child types. I can have one removed since they don't really add much to the testing. So will keep only the `success` variant for both.

2022-07-30 19:14 UTC, jennchenn requested changes

2022-07-30 19:14 UTC, jennchenn commented on backend/python/app/services/implementations/concern_service.py
>                  concern=familial_concern_upper
right now, it looks like `get_familial_concern` and `get_child_concern` are doing the same things

you should add in a `type=` in the filter to differentiate if you would like to keep this methods separate

2022-07-30 19:14 UTC, jennchenn commented on backend/python/app/services/interfaces/concern_service.py
> +        :param concern: string of concern, type: type of concern
```suggestion
        :param concern: string of concern
        :param type: type of concern
```

2022-07-30 19:14 UTC, jennchenn commented on backend/python/app/services/interfaces/concern_service.py
> +        :raises Exception: if concern is invalid
```suggestion
        :raises Exception: if concern is invalid/adding to database fails
```
are we actually doing any validation on the input in the add method right now?

2022-07-30 19:14 UTC, jennchenn commented on backend/python/tests/unit/test_concern_service.py
> +    db.session.bulk_save_objects(familial_concern_instance)
nit: you probably don't need to do this separately anymore since they're all going into the same table but I'm okay with us keeping it like this for now

2022-07-31 00:12 UTC, hamza-yusuff commented on backend/python/app/services/interfaces/concern_service.py
> +        :raises Exception: if concern is invalid
for now I dont think so. I did not see any validation method inside `ConcernDTO` class.

2022-07-31 14:59 UTC, jennchenn commented on backend/python/app/services/implementations/concern_service.py
> +    def get_familial_concern(self, familial_concern, type="FAMILIAL_CONCERN"):
i don't think you should make the `type` a param if this is a function to `get_familial_concern`s only
same thing applies to `get_child_concern` + the `interface` 

i think you'd only want `type` to be a param if this function is `get_concern` in general

2022-07-31 16:12 UTC, jennchenn approved these changes
nice! 🚀

2022-07-31 21:46 UTC, merged