Juthika/ implement formik
uwblueprint/childrens-aid-society pull request #63
Opened 2022-07-29 01:28 UTC by juthikahoque

## Notion ticket link

[Implement Formik](https://www.notion.so/uwblueprintexecs/Task-Board-db95cd7b93f245f78ee85e3a8a6a316d)

## Implementation description
* wrapped each form with formik within the form files
* onSubmit, we set the different form details using state (which exist in the intake page)

## Steps to test
1. checkout branch
2. check that values are being submitted onSubmit (can add a console.log(values) in each of the onSubmits)

## What should reviewers focus on?
* double check whether or not we want to "submit"/save the information when we click the previous and next buttons

## Checklist
- [ ] My PR name is descriptive and in imperative tense
- [ ] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [ ] I have run the appropriate linter(s)
- [ ] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2022-07-30 18:58 UTC, jennchenn requested changes
left some general comments (i only commented on a few spots but the comments apply to any similar implementations)!

2022-07-30 18:58 UTC, jennchenn commented on frontend/src/components/intake/ReferralForm.tsx
> +                />
it doesn't seem like this uses the initial values as expected - should we be using formik `Field` instead?
```
<Field
  as={Input}
  id="referringWorker"
  name="referringWorker"
  type="string"
  placeholder="Enter name of worker..."
  onChange={handleChange}
/>
```

2022-07-30 18:58 UTC, jennchenn commented on frontend/src/components/intake/ReferralForm.tsx
> +  };
does doing this reset the initial values each time the form is rendered? do we not need to pass the initial values into each form from the intake page?

2022-07-30 18:58 UTC, jennchenn commented on frontend/src/components/intake/PermittedIndividualsForm.tsx
> +    React.SetStateAction<PermittedIndividualDetails[]>
are these residual changes from your previous ticket? i don't think introducing `Formik` should introduce changes here

2022-07-30 18:58 UTC, jennchenn commented on frontend/src/components/intake/CourtInformationForm.tsx
> +          >
in the `ReferralForm`, it looks like you do something like this:
`<Button type="submit">Next Button</Button>`

is there a reason why this form is different? i think aiming to keep things consistent would make it easier to understand in the future

2022-07-31 14:53 UTC, juthikahoque commented on frontend/src/components/intake/ReferralForm.tsx
> +  };
i think that it's almost like the useState for initial values where the initial values for the form are only set on the first load

2022-08-11 00:22 UTC, jennchenn approved these changes
I think this looks good! nice work

2022-08-11 01:43 UTC, merged