Updated User Model
uwblueprint/childrens-aid-society pull request #7
Opened 2022-06-01 05:10 UTC by hamza-yusuff

Updated User Model with the roles and branch fields.

## Notion ticket link

[Update User Model] (https://www.notion.so/uwblueprintexecs/Update-user-model-9742b9cab9bb47b9aea46a750f57709f)

## Implementation description
* Added the enum branch field to the user model
* Changed the migration procedure to allow the enum type to be recognised. Made changes to add_user_model.py file at backend/migration/version - had to use alembiac and sqlalchemy.dialects libraries.  Closely followed this link to make the changes - https://stackoverflow.com/questions/37848815/sqlalchemy-postgresql-enum-does-not-create-type-on-db-migrate.

## Steps to test
1.  Access the postgresel database, and run - SELECT * From users; 

## What should reviewers focus on?
* The migration procedure outlined on the project repo could be reviewed, and changed appropriately since the use of enums require manual change of .py migration files generated.

2022-06-01 13:28 UTC, jennchenn requested changes
Nice work on your first PR!!

A few questions/suggestions. Also is the change you made to `db-init/create-multiple-dbs.sh` running `chmod +x`?

2022-06-01 13:28 UTC, jennchenn commented on backend/python/migrations/versions/Add_role_and_branch_to_user_model.py
> +Revision ID: e7f7ce362f62
to make it easier to find the revisions in the future, for now do you want to keep the original filename (i think it should've been something like `e7f7ce362f62_add_driver_role_and_branch_to_user_model.py`)? we can edit the `alembic.ini` file later if we find that there's another format we'd like the files to have (we should also edit the existing versions in that case so they're consistent with whatever new naming convention we choose)

2022-06-01 13:28 UTC, jennchenn commented on backend/python/migrations/versions/Add_role_and_branch_to_user_model.py
> +    op.drop_column("users", "branches")
```suggestion
    op.drop_column("users", "branch")
```

2022-06-01 13:28 UTC, jennchenn commented on backend/python/migrations/versions/Add_role_and_branch_to_user_model.py
> +    op.drop_column("users", "branches")
If I'm reading your model file correctly, I think the column name should be `branch` (and the enum name is `branches`?)

2022-06-01 13:28 UTC, jennchenn commented on backend/python/migrations/versions/Add_role_and_branch_to_user_model.py
> +
it looks like the change to the user didn't get picked up:
```suggestion
     op.execute("ALTER TYPE roles ADD VALUE 'Driver'")
```

2022-06-01 13:28 UTC, jennchenn commented on backend/python/migrations/versions/Add_role_and_branch_to_user_model.py
> +    branches_stat.create(op.get_bind())
if you remove these two lines, does the enum not get created properly? i'm taking a look at the initial migration file since they also add an enum, and it doesn't look like they use `op.get_bind()` https://github.com/uwblueprint/childrens-aid-society/blob/0c7838db69596a1b3d45f7d70f0be8bd6492ee8b/backend/python/migrations/versions/dedc5f7be10c_initial_migration.py#L38

2022-06-01 13:28 UTC, jennchenn commented on backend/python/migrations/versions/Add_role_and_branch_to_user_model.py
> +    branches_stat.drop(op.get_bind())
i think you may be able to change this to:
`op.execute("DROP TYPE branches")`

2022-06-01 13:28 UTC, jennchenn commented on backend/python/migrations/versions/Add_role_and_branch_to_user_model.py
> +
similarly in downgrade you would need to add code to remove the `Driver`... it may look something like this (taken from https://medium.com/makimo-tech-blog/upgrading-postgresqls-enum-type-with-sqlalchemy-using-alembic-migration-881af1e30abe)
```
op.execute("ALTER TYPE roles RENAME TO roles_old")
op.execute("CREATE TYPE roles AS ENUM('User', 'Admin')")
op.execute((
        "ALTER TABLE users ALTER COLUMN role TYPE roles USING "
        "roles::text::roles"
    ))
op.execute("DROP TYPE roles_old")
```

2022-06-01 17:20 UTC, hamza-yusuff commented on backend/python/migrations/versions/Add_role_and_branch_to_user_model.py
> +    op.drop_column("users", "branches")
Yess sorry about that should have tested the function

2022-06-02 00:31 UTC, jennchenn commented on backend/python/migrations/versions/Add_role_and_branch_to_user_model.py
> +Revises: 2d6c26fde419
```suggestion
Revises: 797bfedc3a06
```

2022-06-02 01:05 UTC, jennchenn requested changes
few more changes!

2022-06-02 01:05 UTC, jennchenn commented on backend/python/migrations/versions/e7f7ce362f62_Add_role_and_branch_to_user_model.py
> +Revises: 2d6c26fde419
nit:
```suggestion
Revises: 797bfedc3a06
```

2022-06-02 01:05 UTC, jennchenn commented on backend/python/migrations/versions/e7f7ce362f62_Add_role_and_branch_to_user_model.py
> +def downgrade():
I think you'll need to add commands here to revert the changes to the roles enum (see my previous comment) https://github.com/uwblueprint/childrens-aid-society/pull/7#discussion_r886794991

2022-06-02 01:25 UTC, hamza-yusuff commented on backend/python/migrations/versions/e7f7ce362f62_Add_role_and_branch_to_user_model.py
> +def downgrade():
Sorry about that!

2022-06-02 02:46 UTC, jennchenn requested changes

2022-06-02 02:46 UTC, jennchenn commented on backend/python/migrations/versions/e7f7ce362f62_Add_role_and_branch_to_user_model.py
> +        ("ALTER TABLE users ALTER COLUMN role TYPE roles USING " "roles::text::roles")
your command didn't work for me, but this did:
`op.execute("ALTER TABLE users ALTER COLUMN role TYPE roles USING role::text::roles")`

try upgrading/downgrading and see if it works for you

2022-06-05 15:08 UTC, jennchenn commented on backend/python/migrations/versions/e7f7ce362f62_Add_role_and_branch_to_user_model.py
> +    op.execute("ALTER TABLE users ALTER COLUMN role TYPE roles USING role::text::roles")
```suggestion
    op.execute("ALTER TYPE roles RENAME TO roles_old")
    op.execute("CREATE TYPE roles AS ENUM('User', 'Admin')")
    op.execute("ALTER TABLE users ALTER COLUMN role TYPE roles USING role::text::roles")
    op.execute("DROP TYPE roles_old")
```

2022-06-05 16:50 UTC, jennchenn approved these changes

2022-06-05 16:50 UTC, jennchenn commented
lgtm nice work!!! 🚢

2022-06-05 16:53 UTC, merged