create custom input and change all inputs to custom
uwblueprint/childrens-aid-society pull request #73
Opened 2022-08-18 01:27 UTC by juthikahoque

## Notion ticket link

[Create Custom Input Component](https://www.notion.so/uwblueprintexecs/Task-Board-db95cd7b93f245f78ee85e3a8a6a316d)

## Implementation description
* created a custom input component under common components
* added forwardRef so that we can pass in the ref prop needed for attaching a new file in CourtDetailsForm.tsx

## Steps to test
1. checkout branch
2. check homepage for input with an icon and intake page for input without an icon

<img width="835" alt="Screen Shot 2022-08-17 at 9 24 37 PM" src="https://user-images.githubusercontent.com/77185514/185271680-a75f1cf7-085b-47f5-b58c-a3a8661d76e0.png">

## What should reviewers focus on?
* if the component is placed in the right spot
* if the component looks good -> i had to disable eslint to pass in the props using the spread operator (since that's the easiest way to pass props into the Input component without making anything mandatory/missing any props)

## Checklist
- [ ] My PR name is descriptive and in imperative tense
- [ ] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [ ] I have run the appropriate linter(s)
- [ ] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2022-08-21 16:28 UTC, jennchenn requested changes
thoughts on removing the `ref` and using the normal `Input` component for court order referral attachment? it doesn't really fall into the regular text input category, and that'll help simplify the `CustomInput` component code

2022-08-21 16:28 UTC, jennchenn commented on frontend/src/components/common/CustomInput.tsx
> +type CustomInputProps = {
typescript allows you to compose a type as as an intersection of types (more info [here](https://www.typescriptlang.org/docs/handbook/2/objects.html#intersection-types))

have you tried importing `ImportProps` here like
`type CustomInputProps = ImportProps & { ....`

i don't think this'll solve the eslint issue, but might help scope down the props we accept?

2022-08-21 16:28 UTC, jennchenn commented on frontend/src/components/common/CustomInput.tsx
> +  [x: string]: unknown;
can you explain what this line is for?

2022-08-21 16:28 UTC, jennchenn commented on frontend/src/components/common/CustomInput.tsx
> +        {icon ? (
can this be simplified with [conditional rendering](https://reactjs.org/docs/conditional-rendering.html)?
i.e.
```
{icon && 
     <InputLeftElement pointerEvents="none">{icon}</InputLeftElement>
}

2022-08-23 01:50 UTC, juthikahoque commented on frontend/src/components/common/CustomInput.tsx
> +  [x: string]: unknown;
this is for the ...props paramater

2022-08-25 21:49 UTC, jennchenn approved these changes
nice!

2022-08-27 17:34 UTC, merged