Add intake header component
uwblueprint/childrens-aid-society pull request #75
Opened 2022-08-21 18:02 UTC by thrvg

## Notion ticket link

[Create intake form header component](https://www.notion.so/uwblueprintexecs/134e1f159caa4f73939d11a700c325ad?v=39cf7d5a98384eb9af2bff2265d0ac8a&p=723bcce645c94ce892e16f27a41264ce&pm=s)

## Implementation description
* Added IntakeHeader component which has data passed down from props
* Specified appropriate types
* Used Chakra UI for design

## Steps to test
1. Run the docker container and go to `localhost:3000/intake`

## What should reviewers focus on?
* Screenshot in Notion ticket

## Checklist
- [x] My PR name is descriptive and in imperative tense
- [x] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [x] I have run the appropriate linter(s)
- [x] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2022-08-23 03:18 UTC, jennchenn requested changes
looking good! few changes + questions

2022-08-23 03:18 UTC, jennchenn commented on frontend/src/components/intake/IntakeHeader.tsx
> +};
why did you choose to make this extra type here (i.e. why can't we just have the two titles passed in as props directly?)

2022-08-23 03:18 UTC, jennchenn commented on frontend/src/components/intake/IntakeHeader.tsx
> +  biggerMainTitle: string;
nit: can we rename these to something like `mainTitle`/`primaryTitle` and `subTitle`/`secondaryTitle` or something along those lines?

2022-08-23 03:18 UTC, jennchenn commented on frontend/src/components/intake/IntakeHeader.tsx
> +      <Text textStyle="body-medium">{intakeHeaderText.smallerTopTitle}</Text>
```suggestion
      <Text textStyle="title-small">{intakeHeaderText.smallerTopTitle}</Text>
```

2022-08-23 03:18 UTC, jennchenn commented on frontend/src/components/intake/IntakeHeader.tsx
> +      <Heading textStyle="header-large">
```suggestion
      <Heading textStyle="display-medium">
```

2022-08-23 03:18 UTC, jennchenn commented on frontend/src/components/pages/IntakePage.tsx
> +      <IntakeHeader intakeHeaderText={intakeHeaderText} />
we need a way of allowing the header to change as we move through different forms -> one way this could be done is having the header rendered in each case in the switch statement; alternatively you can keep what you have but change the values of the titles in each case (if you could just add an example of this that'd be great!!)

2022-08-23 03:18 UTC, jennchenn commented on frontend/src/components/intake/IntakeHeader.tsx
> +      <Text textStyle="body-medium">{intakeHeaderText.smallerTopTitle}</Text>
this should be color `gray.600`

2022-08-23 03:18 UTC, jennchenn commented on frontend/src/components/intake/IntakeHeader.tsx
> +      <Heading textStyle="header-large">
this should be color `black`

2022-09-09 20:00 UTC, thrvg commented on frontend/src/components/intake/IntakeHeader.tsx
> +};
I debated doing that, but decided to do it that way to keep it consistent with other components. I could change it :)

2022-09-09 20:39 UTC, thrvg commented on frontend/src/components/intake/IntakeHeader.tsx
> +      <Heading textStyle="header-large">
I did not understand. It should be black instead of grey?

2022-09-09 20:43 UTC, thrvg commented on frontend/src/components/intake/IntakeHeader.tsx
> +      <Text textStyle="body-medium">{intakeHeaderText.smallerTopTitle}</Text>
gray.600 seems very dark

2022-09-09 20:46 UTC, thrvg commented on frontend/src/components/intake/IntakeHeader.tsx
> +      <Text textStyle="body-medium">{intakeHeaderText.smallerTopTitle}</Text>
I ran an eye dropper on the Figma, and correlated it with the colors already defined

2022-09-16 03:53 UTC, jennchenn approved these changes

2022-09-16 03:53 UTC, merged