Setup intake enum field values
uwblueprint/childrens-aid-society pull request #77
Opened 2022-08-30 04:06 UTC by hamza-yusuff

## Notion ticket link

[Setup intake enum field values](https://www.notion.so/uwblueprintexecs/Setup-intake-enum-field-values-5b93660c622a4efc94ec25d79059d410)

## Implementation description
* Updated enum values in `intake` and `caregiver`
* Added new enum values in `intake`

## Steps to test
1.

## What should reviewers focus on?
* 

## Checklist
- [X] My PR name is descriptive and in imperative tense
- [X] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [X] I have run the appropriate linter(s)
- [X] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2022-09-08 21:25 UTC, jennchenn requested changes
looking good! few updates + please change all enum values to be snake cased

2022-09-08 21:25 UTC, jennchenn commented on backend/python/app/models/caregiver.py
> +    "BIOLOGICAL FAMILY",
these should be the only options in this enum

can you also update to have `_` between the words?

2022-09-08 21:25 UTC, jennchenn commented on backend/python/app/models/intake.py
> +    "APPROVE",
remove

2022-09-08 21:25 UTC, jennchenn commented on backend/python/app/models/intake.py
> +    name="intakes_court_status",
please update to have `_` between words

2022-09-08 21:25 UTC, jennchenn commented on backend/python/app/models/intake.py
> +    "FIRST NATION REGISTERED",
add `_` between words

2022-09-18 14:58 UTC, hamza-yusuff commented
> looking good! few updates + please change all enum values to be snake cased

So if it's all caps and has '_' instead of space, it would still be considered snake cased right?

2022-09-18 15:01 UTC, hamza-yusuff commented on backend/python/app/models/intake.py
> +    "APPROVE",
it's only "APPROVE" that need to be removed right?

2022-09-18 16:40 UTC, jennchenn approved these changes
lgtm!

2022-09-18 16:49 UTC, merged