[WIP] Add Query for Goals Given Intake ID
uwblueprint/childrens-aid-society pull request #83
Opened 2022-09-25 17:02 UTC by andrew-y-ma

## Notion ticket link
[Get goals given intake id](https://www.notion.so/uwblueprintexecs/Get-goals-given-intake-id-b4fc9040c686407ea0eef1f63b61e55f)

## Implementation description
* In Goal service, query intake by ID, then return all goals associated with returned intake

## Steps to test
1. Verify all python unit tests run accordingly
2. Verify db upgrade and downgrade are not broken by changes

## What should reviewers focus on?
* Have to add more test cases. Once this is done, verify test coverage is complete

## Checklist
- [ ] My PR name is descriptive and in imperative tense
- [ ] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [ ] I have run the appropriate linter(s)
- [ ] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2022-10-02 16:20 UTC, jennchenn requested changes
few questions!

2022-10-02 16:20 UTC, jennchenn commented on backend/python/app/services/interfaces/goal_service.py
>          pass
add docstrings here explaining the method (same as above)

2022-10-02 16:20 UTC, jennchenn commented on backend/python/tests/functional/test_goal_service.py
> +    intakes_goals.delete()
is this line doing anything?

2022-10-02 16:20 UTC, jennchenn commented on backend/python/tests/functional/test_goal_service.py
> +    db.session.flush()
is this line necessary?

2022-10-02 17:03 UTC, kabiroberai commented on backend/python/tests/functional/test_goal_service.py
> +    intakes_goals.delete()
<img width="496" alt="Stop he's already dead" src="https://user-images.githubusercontent.com/12706786/193466633-d2b21d4e-1e2f-4634-bb3f-73f4d64c6bfc.png">

2022-10-02 17:04 UTC, kabiroberai commented on backend/python/tests/functional/test_goal_service.py
> +    intakes_goals.delete()
https://youtu.be/qQ6wSei-NJU?t=67

2022-10-05 00:05 UTC, andrew-y-ma commented on backend/python/tests/functional/test_goal_service.py
> +    intakes_goals.delete()
LOL I'll check if it works without

2022-10-05 00:25 UTC, andrew-y-ma commented on backend/python/tests/functional/test_goal_service.py
> +    db.session.flush()
Nope, just removed

2022-10-05 12:08 UTC, jennchenn approved these changes
minor nits otherwise looks good! going to give it a premature approval - feel free to merge once you make the changes

2022-10-05 12:08 UTC, jennchenn commented on backend/python/app/services/interfaces/goal_service.py
> +        :param intake_id: int of intake ID
add `:param type:`

2022-10-05 12:08 UTC, jennchenn commented on backend/python/app/services/interfaces/goal_service.py
> +        :raises Exception: if goal or intake is invalid
nit: maybe something like 
```suggestion
        :raises Exception: If intake ID does not exist
```

2022-10-09 15:18 UTC, merged