Convert Court Information page to hi-fi
uwblueprint/childrens-aid-society pull request #88
Opened 2022-10-02 02:03 UTC by kabiroberai

## Notion ticket link

[Convert Court Information page to hi-fi](https://www.notion.so/uwblueprintexecs/Convert-Court-Information-page-to-hi-fi-08e57388560b4f6dba1d46ff930303a1)

## Implementation description
* Introduce new `Autocomplete*` components built on top of Formik + Chakra's Popover
* Bring court info page up to spec

## Steps to test
Go to the Court Information page of `/intake`.

## What should reviewers focus on?
* One design decision worth discussing: I opted to use `<select>` rather than our custom popover for the First Nation Heritage dropdown, since afaict it has the exact semantics of `<select>` in that you can only choose from one of the pre-defined options. Using the intended component here gives us better accessibility + UX out of the box, but I can create a new select-like autocomplete component if it's important that the design be to-spec.

## Checklist
- [x] My PR name is descriptive and in imperative tense
- [x] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [x] I have run the appropriate linter(s)
- [x] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2022-10-05 01:24 UTC, kabiroberai commented
This PR also tackles some bits of this ticket now since the changes were relatively interlinked: [Make minor cosmetic changes to intake hi-fi](https://www.notion.so/uwblueprintexecs/Make-minor-cosmetic-changes-to-intake-hi-fi-7fd548579ecb464690e588007026e50b)

2022-10-05 11:59 UTC, jennchenn requested changes
this is looking really good! some comments/questions 

can you just confirm all changes requested in `Make minor cosmetic changes to intake hi-fi` should be in this branch? i haven't commented on it yet just in case you were planning to separate some of it out

2022-10-05 11:59 UTC, jennchenn commented on frontend/src/components/intake/Autocomplete.tsx
> +    <PopoverContent
how much work would it be to use the `CustomTag` item that @juliannejorda setup? (you can of course make changes to it)

thought behind this is that separating it out will make it easier to reuse for dropdowns as well, but curious what your thoughts are on this

https://github.com/uwblueprint/childrens-aid-society/blob/main/frontend/src/components/common/CustomTag.tsx

2022-10-05 11:59 UTC, jennchenn commented on frontend/src/components/intake/Autocomplete.tsx
> +      sx={{ ":hover, :focus": { backgroundColor: "gray.100" } }}
can we make this a new variant for this and put it here https://github.com/uwblueprint/childrens-aid-society/tree/main/frontend/src/theme

2022-10-05 11:59 UTC, jennchenn commented on frontend/src/components/intake/Autocomplete.tsx
> +  hints,
nit: i think `hints` can be renamed -> `suggestions` / `options` / anything else you think is more descriptive

2022-10-05 11:59 UTC, jennchenn commented on frontend/src/components/intake/CourtInformationForm.tsx
> +                  variant="ghost"
change to `variant="tertiary"` 

https://github.com/uwblueprint/childrens-aid-society/blob/48f264af53cfca66d811553e212dc8b4065764fb/frontend/src/theme/buttonStyles.tsx#L58-L70

2022-10-05 11:59 UTC, jennchenn commented on frontend/src/components/intake/Autocomplete.tsx
> +export const CustomSelectField = ({
can we move this into its own file?

2022-10-05 11:59 UTC, jennchenn commented on frontend/src/components/intake/Autocomplete.tsx
> +export const AutocompleteField = ({
nit: not sure if `AutocompleteField` makes the most sense to me - thoughts on renaming to something like `CustomSelectionField` (and then `CustomSelect` can be renamed to something like `CustomDropdown`?

2022-10-05 11:59 UTC, jennchenn commented on frontend/src/components/intake/Autocomplete.tsx
> +    <Select
can you do a bit of investigation into the effort required to convert this into the custom dropdown matching the figma specs + to keep keyboard/screen reader navigation? you don't have to actually do the work in this branch (i will make a ticket for creating multi-select input fields anyway), but curious to know if it's a big/small lift

2022-10-05 11:59 UTC, jennchenn commented on frontend/src/components/intake/Autocomplete.tsx
> +        {hints.map((hint, index) => (
ideally if an item is selected an a user clicks on the field again, i think it should show the full list of options + an [active SelectionItemContainer](https://www.figma.com/file/Pi7j5EmcROKxGE3eUFGhDK/0.-Libraries-%3E-CAS-Design-system?node-id=746%3A10429) to indicate the current selection rather than filtering everything out

^ but let me know if this requires a lot of rework

2022-10-13 19:17 UTC, jennchenn commented on frontend/src/components/intake/CourtInformationForm.tsx
> +
since we will have more than one optional field, do you think it'd make sense to extract this out into another component (e.g. an `OptionalFormLabel` component that'll just add this optional tag after the form label?)

2022-11-13 16:57 UTC, kabiroberai commented on frontend/src/components/intake/Autocomplete.tsx
> +export const AutocompleteField = ({
The semantic distinction between "Select" and "Autocomplete" is that the latter allows users to enter values that don't match the suggestions, whereas the former has to have a value that's one of the options. That's the same reason I've used the term `hints` instead of `options`, but if you have a strong pref I can still rename this.

2022-11-13 17:02 UTC, kabiroberai commented on frontend/src/components/intake/Autocomplete.tsx
> +    <Select
Getting an MVP working would probably be a 2-story-points kinda task, though keyboard navigation/a11y would definitely require greater eng lift. Still worth doing imo, I'd estimate a couple of hours to get it in a polished state.

2022-11-13 17:47 UTC, kabiroberai commented on frontend/src/components/intake/Autocomplete.tsx
> +    <PopoverContent
Done, I also made the component optionally controllable so that clients can read/write the `pressed` prop.

2022-11-20 16:24 UTC, jennchenn approved these changes
going to approve this for now so we can get it merged in, thanks for all the great work!!!

do you mind going through and adding `# TODO` comments to the changes you did not address--i will document those in a ticket after

2022-12-07 01:27 UTC, merged