[kai/caregiver-route] Add /caregiver route
uwblueprint/childrens-aid-society pull request #90
Opened 2022-10-09 04:51 UTC by kai-wei-mo

## Notion ticket link

[Implement POST /caregiver route](https://www.notion.so/uwblueprintexecs/Implement-POST-caregiver-route-7670810e31e64c22bf7a350f32cfe025)

## Implementation description
* still a work in progress. making a pr for visibility.

## Steps to test
1.

## What should reviewers focus on?
* 

## Checklist
- [ ] My PR name is descriptive and in imperative tense
- [ ] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [ ] I have run the appropriate linter(s)
- [ ] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2022-10-16 21:23 UTC, jennchenn commented
just converting this as a draft for now -- feel free to change it to ready for review whenever!

2022-10-22 22:52 UTC, kai-wei-mo commented on backend/python/app/rest/__init__.py
>      app.register_blueprint(visit_routes.blueprint)
alphabetizing (i don't think that changing the order of registration breaks anything)

2022-10-22 22:54 UTC, kai-wei-mo commented on backend/python/app/rest/caregiver_routes.py
> +# @require_authorization_by_role({"Admin"})
should this be uncommented?

2022-10-22 22:56 UTC, kai-wei-mo commented on backend/python/app/rest/caregiver_routes.py
> +# @require_authorization_by_role({"Admin"})
should this be uncommented?

2022-10-22 22:56 UTC, kai-wei-mo commented on backend/python/app/rest/caregiver_routes.py
> +# @validate_request("CreateCaregiverDTO")
should this be uncommented?

2022-10-22 22:56 UTC, kai-wei-mo commented on backend/python/app/services/implementations/user_service.py
> -        user_list = [result for result in User.query.all()]
i think this is a no-op

2022-10-22 22:56 UTC, kai-wei-mo commented on backend/python/app/rest/__init__.py
>      app.register_blueprint(visit_routes.blueprint)
alphabetizing (i don't think changing the registration order breaks anything)

2022-10-22 22:56 UTC, kai-wei-mo commented on backend/python/tools/db_seed.py
> +    db.engine.execute("TRUNCATE TABLE users RESTART IDENTITY CASCADE")
alphabetizing

2022-10-23 17:47 UTC, jennchenn requested changes
> question: the case where the caretaker table does not exist and we try to POST is not considered. this is because a valid caretaker creation needs a children foreign key. and if children exists, caretaker table should exist too. is this ok?
yup this is fine, you can assume the tables exist

> when testing POST, the tester needs to run the curl command 3 times because the first and second runs do not see the existing 2 caretakers created by the seed script. how to fix this?
mentioned during call, but removing the hardcoded `id`s in the seed script seems to make this error go away!

2022-10-23 17:47 UTC, jennchenn commented on backend/python/app/services/implementations/caregiver_service.py
> +            caregivers_dto = [CaregiverDTO(**x.to_dict()) for x in caregivers]
nit
```suggestion
            caregivers_dto = [CaregiverDTO(**caregiver.to_dict()) for caregiver in caregivers]
```

2022-10-23 17:47 UTC, jennchenn commented on backend/python/app/rest/caregiver_routes.py
> +        return jsonify(error), 400
i think we need this to be converted to `str` for the error to be json serializable

2022-10-23 17:47 UTC, jennchenn commented on backend/python/app/rest/caregiver_routes.py
> +# @validate_request("CreateCaregiverDTO")
yes - we can validate the request but keep `require_auth...` commented out for now

2022-10-23 17:47 UTC, jennchenn commented on backend/python/app/rest/caregiver_routes.py
> +# @validate_request("CreateCaregiverDTO")
`validate_request` happens here: https://github.com/uwblueprint/childrens-aid-society/blob/main/backend/python/app/middlewares/validate.py

2022-10-23 17:47 UTC, jennchenn commented on backend/python/app/services/implementations/caregiver_service.py
> +    def get_all_caregivers(self):
do you mind adding a comment here: `FIXME: change this to match spec for actual get caregivers method`

2022-10-23 17:47 UTC, jennchenn commented on backend/python/tools/db_seed.py
> +        insert_values(db, "caregivers", ("id", "type", "first_name", "last_name", "is_primary", "child_id", "address_id", "relationship_to_child", "phone_number", "cpin_number", "date_of_birth", "spe
for all the inserts in this file, remove the `id` column

2022-10-25 15:20 UTC, jennchenn approved these changes
tested changes and it looks good! just one nit

2022-10-25 15:20 UTC, jennchenn commented on backend/python/app/services/implementations/caregiver_service.py
> +
nit: i think we are running the rest of the app under the assumption that the database is up and running (or else we will have a lot of errors everywhere else) so not sure if you need this

2022-10-26 00:10 UTC, merged