Create Individual Details Entrypoint
uwblueprint/childrens-aid-society pull request #93
Opened 2022-10-23 18:20 UTC by andrew-y-ma

## Notion ticket link
[Build out Individual Details flow entrypoint](https://www.notion.so/uwblueprintexecs/Build-out-Individual-Details-flow-entrypoint-8c88ac1156fe4e74984111ecd9671295)

## Implementation description
* Created new IndividualDetailsEntry and PromptBox components
* React router link to Individual details entry page

## Steps to test
1. Go to http://localhost:3000/intake
2. Press next button until individual details entry is reached
3. Verify design aligns with [Figma](https://www.figma.com/file/1obAgfYZ639hpKXV1ZP7hJ/3.-FeatureSets-%3E-Case-intake?node-id=1175%3A19815)
4. Verify add child button navigates to new page
5. Verify add caregiver button navigates to new page

## What should reviewers focus on?
* Naming for PromptBox component
* Where should UserPlusIcon be in the repo

## Checklist
- [ ] My PR name is descriptive and in imperative tense
- [ ] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [ ] I have run the appropriate linter(s)
- [ ] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2022-10-25 15:14 UTC, jennchenn requested changes
looks good! some changes requested

also we seem to have a mismatch in prettier versions so there are a bunch of linting errors :( to fix this, in the frontend container run `yarn fix` and commit (if you have to make changes to a file after this command, make sure you `Save without formatting`)

2022-10-25 15:14 UTC, jennchenn commented on frontend/src/components/intake/PromptBox.tsx
> +import { UserPlusIcon } from "./UserPlusIcon";
this can actually be replaced by the feather icon https://feathericons.com/?query=user-plus

should be something like: `import { UserPlus } from "react-feather";`

2022-10-25 15:14 UTC, jennchenn commented on frontend/src/components/intake/PromptBox.tsx
> +      </Link>
since we want to reuse this component for other pages (e.g. when adding providers), perhaps passing in an `onClick` function would make more sense than hardcoding the link here

2022-10-30 15:53 UTC, jennchenn commented on frontend/src/components/intake/IndividualDetailsEntry.tsx
> +import { useRouteMatch } from "react-router-dom";
for consistency with other pages, can you do the following instead:
```
import { useHistory } from "react-router-dom";
...

const IndividualDetailsEntry = ({
  nextStep,
  prevStep,
}: IndividualDetailsEntryProp): React.ReactElement => {
  const history = useHistory();
  return (
...

onButtonClick={() => {
     history.push(INDIVIDUAL_DETAILS_PAGE);
}}
```

2022-10-30 15:55 UTC, andrew-y-ma commented on frontend/src/components/intake/IndividualDetailsEntry.tsx
> +import { useRouteMatch } from "react-router-dom";
yup will do!

2022-10-30 16:25 UTC, jennchenn approved these changes
lgtm!

2022-10-30 16:26 UTC, merged