[kai/diff-caregiver-and-provider] Update models caregiver and provider
uwblueprint/childrens-aid-society pull request #94
Opened 2022-10-23 21:22 UTC by kai-wei-mo

## Notion ticket link

[Differentiate caregiver/provider models](https://www.notion.so/uwblueprintexecs/Differentiate-caregiver-provider-models-eeabe6bb96e540b0959289bd00a19f1b)

## Implementation description
* **work in progress. do not review or merge.**

## Steps to test
1.

## What should reviewers focus on?
* 

## Checklist
- [ ] My PR name is descriptive and in imperative tense
- [ ] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [ ] I have run the appropriate linter(s)
- [ ] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2022-10-23 21:33 UTC, kai-wei-mo commented on backend/python/app/models/caregiver.py
>      # TODO: add foreign key reference to child
is this todo still relevant after these changes?

2022-10-23 21:35 UTC, kai-wei-mo commented on backend/python/app/models/provider.py
> +    relationship_to_child = db.Column(db.String, nullable=False)
should this be a `relationship_to_child_enum` instead?

2022-10-26 04:14 UTC, kai-wei-mo commented on backend/python/app/resources/caregiver_dto.py
> +            #         "primary_phone_number must be in the format XXX-XXX-XXXX"
do we have any convention for storing phone numbers?

2022-10-29 05:29 UTC, kai-wei-mo commented on backend/python/tools/db_seed.py
> +        insert_values(db, "caregivers", ("name", "date_of_birth", "individual_considerations", "primary_phone_number", "secondary_phone_number", "email", "address", "relationship_to_child", "addition
this was done as a result of https://github.com/uwblueprint/childrens-aid-society/pull/91 being merged into master. it is not related to the ticket at task

2022-10-30 17:00 UTC, jennchenn requested changes
some changes requested!

2022-10-30 17:00 UTC, jennchenn commented on backend/python/app/resources/caregiver_dto.py
> +import re
what is this import for?

2022-10-30 17:00 UTC, jennchenn commented on backend/python/app/resources/caregiver_dto.py
> +            #         "primary_phone_number must be in the format XXX-XXX-XXXX"
not right now - perhaps just checking for string, number, hyphen (we should allow characters in case they write 'ext')

2022-10-30 17:00 UTC, jennchenn commented on backend/python/tools/db_seed.py
> +        insert_values(db, "caregivers", ("name", "date_of_birth", "individual_considerations", "primary_phone_number", "secondary_phone_number", "email", "address", "relationship_to_child", "addition
thank you for catching this!

2022-10-30 17:00 UTC, jennchenn commented on backend/python/migrations/versions/2022-10-29_6138c8f35f13_differential_caregiver_and_provider_.py
> +"""differential caregiver and provider models
one step for migration:
> When making database changes, a new migration must be generated. Import any new model files into [backend/python/app/models/__init__.py](https://github.com/uwblueprint/childrens-aid-society/blob/main/backend/python/app/models/__init__.py) and run: 
>```
>docker exec -it cas_py_backend /bin/bash -c "flask db migrate -m '<short description of the migration>'"
>```

do you mind deleting this migration file and doing the import first before regenerating (i was planning to create a migration on all the changes once all the small db changes are done so you technically don't have to do one here)

2022-10-30 22:23 UTC, kai-wei-mo commented on backend/python/app/resources/caregiver_dto.py
> +import re
this is a regex library that i was going to use to match phone numbers. i will remove this (and the phone number matching) because you mentioned that we should allow any character in case users write "ext."

2022-10-30 22:29 UTC, kai-wei-mo commented on backend/python/app/models/caregiver.py
>      # TODO: add foreign key reference to child
is this todo still relevant? @jennchenn

2022-10-31 02:37 UTC, jennchenn approved these changes
going to trust that you've checked that `flask db upgrade` works fine on your migration!

you can remove the outdated todo and should be good to merge

2022-10-31 02:37 UTC, jennchenn commented on backend/python/app/models/caregiver.py
>      # TODO: add foreign key reference to child
nope you can remove !!

2022-10-31 17:53 UTC, merged