[kai/delete-address-table] Delete address table
uwblueprint/childrens-aid-society pull request #96
Opened 2022-11-01 00:31 UTC by kai-wei-mo

## Notion ticket link

[Remove address table and references](https://www.notion.so/uwblueprintexecs/Remove-address-table-and-references-f905caf33cc4482bb8a7dfae291276f2)

## Implementation description
* Delete the `address` model and table
* as well as anything that references/uses `address`
* Now, `address` is a `string` field instead of a `fk`

## Steps to test
1.

## What should reviewers focus on?
* 

## Checklist
- [x] My PR name is descriptive and in imperative tense
- [x] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [x] I have run the appropriate linter(s)
- [x] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2022-11-02 02:00 UTC, jennchenn requested changes
getting some errors with running the migration but otherwise looks like you've found most of the references to the address table!

2022-11-02 03:47 UTC, kai-wei-mo commented on backend/python/app/resources/daytime_contact_dto.py
> +import string
i have no idea how that got there LOL

2022-11-02 03:50 UTC, kai-wei-mo commented on backend/python/migrations/versions/2022-11-01_967df97c58f0_remove_address_table.py
> +"""remove address table
should be fixed now, thanks!

2022-11-02 03:50 UTC, kai-wei-mo commented on backend/python/tools/db_seed.py
>      for value in values:
fixed now, thanks!

2022-11-06 16:38 UTC, jennchenn approved these changes
upgrade works now, nice work!!!

2022-11-06 23:45 UTC, merged