[kai/update-intake-model] Update intake model
uwblueprint/childrens-aid-society pull request #97
Opened 2022-11-02 04:13 UTC by kai-wei-mo

## Notion ticket link

[Update intake model](https://www.notion.so/uwblueprintexecs/Update-intake-model-775ae158aaea4c0d8b60485f0ed92e46)

## Implementation description
* Update the intake model per the specifications of the Notion ticket

## Steps to test
1. No testing, just visual inspection

## What should reviewers focus on?
* N/A

## Checklist
- [x] My PR name is descriptive and in imperative tense
- [x] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [x] I have run the appropriate linter(s)
- [x] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2022-11-02 04:14 UTC, kai-wei-mo commented on backend/python/app/models/intake.py
> +    """
i left these comments here as a visual aid, i will remove them before merging

2022-11-02 04:32 UTC, kai-wei-mo commented
my created migration is invalid. when i run `docker exec -it cas_py_backend /bin/bash -c "flask db upgrade"`, i see:

```
...
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedObject) type "cpin_file_type" does not exist
LINE 1: ALTER TABLE intakes ADD COLUMN cpin_file_type cpin_file_type...
                                                      ^

[SQL: ALTER TABLE intakes ADD COLUMN cpin_file_type cpin_file_type NOT NULL]
(Background on this error at: http://sqlalche.me/e/13/f405)
```

looking for help on how to debug this after personal attempts have been unsuccessful

2022-11-02 14:30 UTC, jennchenn commented on backend/python/app/models/intake.py
> +intake_status_enum = pg.ENUM(
can you try changing to `db.Enum` and regenerate the migration and see if it helps?

2022-11-02 14:31 UTC, jennchenn commented on backend/python/migrations/versions/2022-11-02_0ebe1c4a11dd_update_intake_model.py
> +        ),
or try this:
```suggestion
        sa.Column(
            "cpin_file_type",
            sa.Enum("INVESTIGATION", "ONGOING", name="cpin_file_type"),
            nullable=False,
        ),
```

2022-11-02 16:50 UTC, kai-wei-mo commented
need to fix ci; i will come back to this later

2022-11-03 06:41 UTC, kai-wei-mo commented on backend/python/app/services/implementations/concern_service.py
> -    def get_concerns_by_intake(self, intake_id, type=None):
concern and intake have nothing to do with each other (neither includes the other as a foreign key)

2022-11-03 06:41 UTC, kai-wei-mo commented on backend/python/app/services/interfaces/concern_service.py
> -    def get_concerns_by_intake(self, intake_id, type=None):
concern and intake have nothing to do with each other (neither includes the other as a foreign key)

2022-11-03 06:42 UTC, kai-wei-mo commented on backend/python/tests/functional/test_concern_service.py
> -from app.models.intake import Intake
concern and intake have nothing to do with each other (neither includes the other as a foreign key)

2022-11-03 06:42 UTC, kai-wei-mo commented on backend/python/tests/functional/test_goal_service.py
> -from app.models.intake import Intake, intakes_goals
goal and intake have nothing to do with each other (neither includes the other as a foreign key)

2022-11-06 17:10 UTC, jennchenn requested changes
some minor changes to nullable / field names

can you please undo the changes to concern and goal for now? they both have a many to many mapping to intake right now (this mapping is specified in the `intakes_concerns` and `intakes_goals` tables you deleted)--this may change in the future but for now let's keep it as is

2022-11-06 17:10 UTC, jennchenn commented on backend/python/app/models/intake.py
> +    access_start_date = db.Column(db.Date, nullable=False)
```suggestion
    transportation_requirements = db.Column(db.String, nullable=False)
    scheduling_requirements = db.Column(db.String, nullable=False)
    suggested_start_date = db.Column(db.Date, nullable=False)
```

2022-11-06 17:10 UTC, jennchenn commented on backend/python/app/models/intake.py
> +    "IN REVIEW",
```suggestion
    "IN_PROGRESS",
    "IN_REVIEW",
```

2022-11-06 17:10 UTC, jennchenn commented on backend/python/app/models/intake.py
> +    intake_status = db.Column(intake_status_enum, nullable=True, default="IN PROGRESS")
```suggestion
    intake_status = db.Column(intake_status_enum, nullable=True, default="IN_PROGRESS")
```

2022-11-06 17:10 UTC, jennchenn commented on backend/python/app/models/intake.py
> +    user_id = db.Column(db.Integer, db.ForeignKey("users.id"), nullable=True)
```suggestion
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"), nullable=False)
```

2022-11-06 17:10 UTC, jennchenn commented on backend/python/app/models/intake.py
>      cpin_number = db.Column(db.String, nullable=True)
```suggestion
    referral_date = db.Column(db.Date, nullable=False)
    family_name = db.Column(db.String, nullable=False)
    cpin_number = db.Column(db.String, nullable=False)
```

2022-11-06 17:10 UTC, jennchenn commented on backend/python/app/models/intake.py
>      court_status = db.Column(court_status_enum, nullable=True)
```suggestion
    court_status = db.Column(court_status_enum, nullable=False)
```

2022-11-06 17:10 UTC, jennchenn commented on backend/python/app/models/intake.py
>      court_order_file = db.Column(db.String, nullable=True)
```suggestion
    court_order_file = db.Column(db.String, nullable=False)
```

2022-11-07 02:47 UTC, kai-wei-mo commented on backend/python/app/services/implementations/concern_service.py
>      def get_concerns_by_intake(self, intake_id, type=None):
this function has been reworked to find concerns given an intake id by using the `intakes_concerns` table

2022-11-07 02:48 UTC, kai-wei-mo commented on backend/python/app/services/implementations/goal_service.py
>      def get_goals_by_intake(self, intake_id, type=None):
this function has been reworked to find goals given an intake id by using the `intakes_goals` table

2022-11-07 02:51 UTC, kai-wei-mo commented on backend/python/tests/functional/test_concern_service.py
> -    },
imo 80 lines of mock data was too overkill and made this file hard to read

2022-11-07 02:57 UTC, kai-wei-mo commented on backend/python/tests/functional/test_concern_service.py
> +    assert sorted([item.id for item in res]) == sorted(concern_ids)
testing that the `id`s are equal in addition to testing equal array lengths is stronger than testing only testing equal array lengths

2022-11-07 02:58 UTC, kai-wei-mo commented on backend/python/tests/functional/test_concern_service.py
> -def test_get_all_concerns_success(concern_service):
this function does not do what its name suggests it does so i renamed it to something more accurate: `test_get_concerns_by_intake_id_success`. then i added a test that actually tests for `test_get_all_concerns_success`

2022-11-07 03:01 UTC, kai-wei-mo commented on backend/python/tests/functional/test_caregiver_service.py
> -    Caregiver.query.delete()
redundant (already done in `teardown_database()`)

2022-11-09 01:50 UTC, jennchenn requested changes
few nits!

2022-11-09 01:50 UTC, jennchenn commented on backend/python/app/models/intake.py
>      denial_reason = db.Column(db.String, nullable=True)
can you add these lines back in:
```
concerns = db.relationship("Concern", secondary=intakes_concerns)
goals = db.relationship("Goal", secondary=intakes_goals)
```

2022-11-09 01:50 UTC, jennchenn commented on backend/python/app/services/implementations/concern_service.py
>      def get_concerns_by_intake(self, intake_id, type=None):
i think these changes can be reverted when the relationship fields are added back in

2022-11-09 01:50 UTC, jennchenn commented on backend/python/app/services/implementations/goal_service.py
>      def get_goals_by_intake(self, intake_id, type=None):
same comment as ^

2022-11-09 01:50 UTC, jennchenn commented on backend/python/migrations/versions/2022-11-07_12e97fac48b2_update_intake_model.py
> +                "IN PROGRESS", "IN REVIEW", "ACCEPTED", "DENIED", name="intake_status"
do you still need to declare the enum here, or can you just pass in the name `intake_status` (since it should already be created?)

2022-11-09 01:50 UTC, jennchenn commented on backend/python/tests/functional/test_concern_service.py
> -def test_get_all_concerns_success(concern_service):
good catch!

2022-11-09 02:50 UTC, jennchenn approved these changes
nice work!

2022-11-09 06:10 UTC, merged